const COURSE_MODULES = [
  {
    id: 'm0', label: '00', title: '学习方法与先修基础', time: '第 0 周', color: 'blue', description: '先建立实验环境、阅读地图和判断问题的能力。',
    lessons: [
      { id: 'm0l1', title: 'AI Agent 的完整心智模型', level: '入门', why: 'Agent 不是一个神秘的“智能体”，而是模型、工具、状态、循环和控制规则组成的程序系统。', learn: ['区分 LLM call、Chain、Workflow、Agent、Multi-agent', '理解 Model / Prompt / Context / Tool / State / Loop 的职责边界', '画出一次请求从输入、决策、工具执行到最终输出的时序图', '判断一个需求应该用固定流程还是模型驱动的流程'], practice: '把“项目管理助手”拆成组件：查询项目、查询任务、创建任务、更新状态、人工确认；为每个动作标出输入、输出和副作用。', acceptance: '能够用一张图解释系统，并指出至少两个不应该交给模型自由决定的步骤。', read: 'LangGraph Graph API：State、Node、Edge 的定义。', links: [{ text: 'LangGraph Graph API', url: 'https://docs.langchain.com/oss/python/langgraph/graph-api' }] },
      { id: 'm0l2', title: '实验环境、模型接口与成本意识', level: '入门', why: '框架问题经常被 API、密钥、模型能力和环境问题掩盖；先建立可重复实验的底座。', learn: ['Python 3.10+、虚拟环境、环境变量和依赖锁定', 'chat completion 的 messages、参数、usage 和错误结构', 'token、上下文窗口、输入输出成本与延迟的关系', '模型能力矩阵：工具调用、结构化输出、视觉、长上下文'], practice: '写一个 `llm_probe.py`：发送同一问题，打印响应、tool_calls、token usage、耗时和错误类型；为它增加超时和重试。', acceptance: '你能区分“模型不会”“请求没发出去”“工具失败”“输出解析失败”四类错误。', read: '建立一个 `experiments/` 目录，每个实验保存输入、配置、输出和结论。' },
      { id: 'm0l3', title: '如何阅读 Agent 框架源码', level: '入门', why: '只会调用高层 API 很难定位 Agent 的真实行为；源码阅读要从调用链和状态边界入手。', learn: ['从 public API 追到 runtime、executor、state 和 persistence', '先读类型定义和协议，再读控制流，最后读 provider adapter', '用最小可运行例子打断点，不从仓库首页漫游', '区分稳定契约、实现细节和可能变化的内部 API'], practice: '选择一个最小 Agent，记录 `input → model request → tool call → tool result → next model request → output` 的调用链。', acceptance: '能指出至少一个框架抽象背后的普通 Python 函数、一个状态对象和一个停止条件。', read: '建议先读 LangGraph 的 `StateGraph` / `Pregel` / checkpoint，再读 LangChain Agent。' }
    ]
  },
  {
    id: 'm1', label: '01', title: 'LLM、Transformer 与推理原理', time: '第 1–2 周', color: 'yellow', description: '不要求手写大模型，但要理解 token 如何变成概率、概率如何变成行为。',
    lessons: [
      { id: 'm1l1', title: 'Tokenization 与上下文窗口', level: '基础', why: 'Prompt 的长度、成本、检索片段和记忆摘要最终都受 token 约束。', learn: ['字符、词、子词 token 与 BPE/SentencePiece 的基本思路', 'token 数不是字符数；中英文、代码、JSON 的 token 密度差异', 'context window 包含 system、历史消息、工具 schema、工具结果和输出预留', '上下文截断、滑动窗口和摘要压缩的基本策略'], practice: '准备一段中文、英文、JSON 和代码，比较 token 数；设计一个“剩余预算不足时”的消息裁剪策略。', acceptance: '能估算一次 Agent loop 的上下文增长，并解释为什么工具 schema 也会消耗上下文。', read: '理解 tokenizer 输出和模型 API usage，不把 token 当作字数。' },
      { id: 'm1l2', title: 'Transformer：从注意力到下一 token', level: '基础', why: '理解 attention、KV cache 和位置编码，才能理解长上下文、延迟和模型为何会“关注”错误内容。', learn: ['Embedding、Q/K/V、scaled dot-product attention', '多头注意力、残差连接、LayerNorm 与 FFN 的作用', '自回归生成：模型每次预测下一个 token', 'KV cache 如何减少重复计算，以及长上下文为什么变慢'], practice: '用 NumPy 实现一个单头 self-attention；打印 attention matrix，观察改变一个 token 后权重如何变化。', acceptance: '能够用公式和直觉解释 `softmax(QKᵀ/√d)V`，并说明它不是数据库检索。', read: '建议阅读《Attention Is All You Need》，再看一个教学 Transformer 实现。' },
      { id: 'm1l3', title: '解码、采样与模型行为', level: '基础', why: 'temperature 不是“智能程度”，top-p 也不是可靠性开关；解码参数影响的是概率分布的选择方式。', learn: ['logits、softmax、temperature 的关系', 'greedy、top-k、top-p、beam search 的差异', '随机性、可重复性和 seed 的限制', '为什么低 temperature 仍可能产生错误'], practice: '对同一问题用不同 temperature/top-p 运行 20 次，记录答案差异；比较事实问答、创作和结构化抽取。', acceptance: '能够为事实抽取、创意写作和 Agent 工具选择分别给出参数策略及理由。', read: '把“模型能力”和“解码策略”分开分析。' },
      { id: 'm1l4', title: '预训练、指令微调与对齐', level: '进阶', why: 'Agent 的工具调用能力来自训练、协议和提示的共同作用，不能只归因于 Prompt。', learn: ['预训练的 next-token prediction', 'SFT、instruction tuning、preference optimization 的高层流程', '工具调用是结构化输出协议，不等于模型真的执行了函数', '拒答、偏好和安全行为的来源及边界'], practice: '构造一个模型“声称调用工具但没有 tool_call”的失败样例，设计解析器和重试策略。', acceptance: '能解释模型输出的 tool call 与真正执行工具之间的安全边界。', read: '重点理解消息协议、schema 校验和执行器，不必一开始深入训练细节。' }
    ]
  },
  {
    id: 'm2', label: '02', title: 'Prompt Engineering', time: '第 3 周', color: 'green', description: '把自然语言指令变成可测试、可迭代、可迁移的行为契约。',
    lessons: [
      { id: 'm2l1', title: 'Prompt 的结构与信息层级', level: '基础', why: '高质量 Prompt 的核心不是“写得长”，而是让任务、数据、约束和输出格式没有歧义。', learn: ['角色、目标、输入、步骤、约束、输出格式的组织方式', 'system 指令、user 数据、tool 结果和引用材料的分隔', '优先级冲突与不可信内容隔离', '为不同用户、租户和任务注入运行时上下文'], practice: '把一个含糊的“请分析这个项目”改成可执行 Prompt：定义输入字段、分析维度、缺失数据处理和 JSON 输出。', acceptance: '用 10 条边界样例证明 Prompt 对空输入、冲突指令和未知信息有明确行为。', read: '把 Prompt 作为版本化配置管理，记录变更原因和评估结果。' },
      { id: 'm2l2', title: 'Few-shot、分解与自检', level: '基础', why: '示例和任务分解能改善格式和流程，但也会扩大上下文并引入示例偏差。', learn: ['few-shot 示例的选择、顺序与覆盖面', '直接回答、分步分解、plan-and-solve 的取舍', '让模型输出检查清单、置信依据或结构化中间结果', '自检不是事实保证，必须结合外部证据或规则校验'], practice: '为分类任务构造正例、边界例和反例；比较 zero-shot、few-shot 和“先分类再解释”。', acceptance: '能用实验数据说明示例提高了什么，而不是只凭主观感受。', read: '避免把“请一步一步思考”当作万能提示；关注可观测的结构化结果。' },
      { id: 'm2l3', title: 'Structured Output 与 Schema', level: '进阶', why: 'Agent 依赖结构化参数；没有 schema 校验，工具调用和业务写入都不可靠。', learn: ['JSON Schema、Pydantic、枚举、必填/可选字段', '解析失败、部分字段缺失和语义校验', '结构化输出与 function/tool calling 的区别', 'schema 演进、兼容性和版本管理'], practice: '定义 `CreateTask` schema：标题、项目 ID、优先级、截止时间、描述；为非法日期、未知项目和重复任务写校验。', acceptance: '模型输出不符合 schema 时，系统能返回可修复的错误并限制重试次数。', read: '将“语法合法”和“业务合法”分开校验。' },
      { id: 'm2l4', title: 'Prompt Evaluation 与迭代', level: '进阶', why: 'Prompt 改动可能改善一个案例却伤害整个分布；需要数据集、指标和回归测试。', learn: ['golden set、边界集、对抗集和线上样本', '准确率、格式遵循、groundedness、拒答率、工具选择准确率', 'LLM-as-judge 的偏差与人工抽检', 'prompt version、实验对照和回归门禁'], practice: '建立 30 条 Agent 测试集，给每条标注预期工具、关键事实和安全边界；每次 Prompt 修改自动比较。', acceptance: '能定位一次指标下降来自 Prompt、模型、检索或工具变化。', read: 'LangSmith 可用于 tracing、evaluation 和 prompt 管理。' }
    ]
  },
  {
    id: 'm3', label: '03', title: 'Embeddings、搜索与 RAG', time: '第 4–5 周', color: 'orange', description: '从文档进入索引，再从问题进入证据，最后生成带来源的答案。',
    lessons: [
      { id: 'm3l1', title: 'Embedding 与向量相似度', level: '基础', why: 'RAG 的“语义搜索”不是魔法；它是表示空间中的近邻检索。', learn: ['embedding 模型把文本映射到向量空间', 'cosine similarity、dot product、L2 distance', '相似不等于相关，领域词汇和数值条件会造成误召回', 'embedding 模型、维度、归一化和版本一致性'], practice: '为 20 条文档问题生成 embedding，手算/实现 cosine similarity，观察相似度最高但答案错误的案例。', acceptance: '能解释为什么“退款 7 天”和“退款 30 天”可能语义相似但业务上不能混用。', read: '将向量检索结果保存下来，先分析召回再分析生成。' },
      { id: 'm3l2', title: '文档解析、切分与 metadata', level: '基础', why: '很多 RAG 失败不是模型问题，而是 PDF 解析、标题层级、表格和 chunk 边界丢失。', learn: ['loader、OCR、版面、表格和代码块处理', '固定长度、递归、语义和结构感知切分', 'chunk size、overlap 与检索粒度的权衡', 'source、page、section、tenant、permission metadata'], practice: '对一份带目录、表格和代码的文档做三种切分，比较命中片段是否包含完整定义和上下文。', acceptance: '每个 chunk 能追溯到原文位置和权限范围；切分失败有可观测日志。', read: '不要只保存纯文本；来源、版本和访问控制是 RAG 数据模型的一部分。' },
      { id: 'm3l3', title: 'Retriever、BM25、Hybrid 与 Rerank', level: '进阶', why: '单纯向量 top-k 对专有名词、ID、版本号和精确条件经常不够。', learn: ['倒排索引和 BM25 的词频/逆文档频率直觉', 'dense retrieval 与 sparse retrieval 的互补', '候选合并、分数归一化和 metadata filter', 'cross-encoder reranker 与召回/排序的职责'], practice: '用 BM25、向量、hybrid 三种方式检索同一测试集；对每条结果标注相关性和答案覆盖度。', acceptance: '能用 recall@k、MRR/nDCG 或人工相关性说明排序策略变化的效果。', read: '优先从检索指标定位问题，别一上来改 Prompt。' },
      { id: 'm3l4', title: '2-Step RAG、Agentic RAG 与引用', level: '进阶', why: '固定检索流程可预测，Agentic RAG 更灵活但会带来额外延迟和不可控性。', learn: ['2-Step：先检索，再生成；延迟和成本可预估', 'Agentic：模型决定是否检索、查什么和查几次', 'Hybrid：查询改写、检索验证、答案验证', '引用绑定、证据不足拒答、冲突来源和时间版本'], practice: '实现一个带引用的 RAG：检索相关性低于阈值时改写一次问题；答案中的每个结论必须对应 source ID。', acceptance: '能区分检索不到、检索错、模型没用证据和引用伪造四类问题。', read: '官方 RAG 文档对三种架构有清晰对比。', links: [{ text: 'LangChain Retrieval', url: 'https://docs.langchain.com/oss/python/langchain/retrieval' }] }
    ]
  },
  {
    id: 'm4', label: '04', title: 'Tool Calling 与 Agent Loop', time: '第 6 周', color: 'purple', description: '理解“模型决定行动”与“系统执行行动”之间的协议和安全边界。',
    lessons: [
      { id: 'm4l1', title: 'Tool 的契约：名称、描述、参数、结果', level: '基础', why: '模型选择工具主要依赖工具名、描述和 schema；工具设计就是 Agent 设计的一部分。', learn: ['工具描述应该告诉模型何时用、何时不用、输入约束和副作用', '参数 schema、默认值、枚举和幂等键', '工具结果的结构化 envelope：data、error、source、metadata', '把内部异常转换成模型可理解但不泄露敏感信息的错误'], practice: '设计 `search_tasks`、`get_project`、`create_task` 三个工具，写正例和反例描述，观察选择变化。', acceptance: '工具边界清楚；模型无法通过自由文本绕过必填参数和权限检查。', read: '工具描述是给模型看的 API 文档，但权限校验必须在服务端执行。' },
      { id: 'm4l2', title: 'ReAct、Function Calling 与状态机', level: '基础', why: 'ReAct 是一种交替推理/行动模式；现代 function calling 把行动意图结构化，但仍需要执行器。', learn: ['Thought/Action/Observation 的概念，不把隐藏思维当作系统事实', 'tool call message、tool result message 和多轮消息协议', '模型输出 → schema 校验 → 工具执行 → 结果回填', '固定状态机和自由 Agent loop 的差异'], practice: '不用框架写一个最多 3 步的 loop：支持工具调用、超时、解析失败重试和最终回答。', acceptance: '能打印每一轮消息，并解释停止发生在模型决策、业务规则还是预算耗尽。', read: '先手写 loop，再用框架；这样才能看懂框架抽象。' },
      { id: 'm4l3', title: 'Loop Engineering：预算、重试与终止', level: '进阶', why: '没有循环边界的 Agent 可能重复搜索、无限调用或无限消耗成本。', learn: ['最大模型调用次数、工具调用次数、总 token 和 wall-clock deadline', '按错误类型区分重试、换工具、询问用户和终止', '去重、幂等、缓存和回退模型', '循环不变量：状态可序列化、每轮有进展、最终可解释'], practice: '为研究 Agent 加上 step budget、deadline、重复 action 检测和失败摘要；构造死循环测试。', acceptance: '任何输入都能在预算内结束，并返回完成、部分完成或失败的原因。', read: '把预算当作运行时策略，不要只写在 Prompt 里。' },
      { id: 'm4l4', title: '副作用、安全与人工确认', level: '进阶', why: '查询和写入的风险不同；Agent 能调用工具不代表它有权执行所有动作。', learn: ['read-only 与 write tool 的分类', '身份、租户、资源权限在工具层再次校验', 'confirmation、preview、approval receipt 与幂等执行', '提示注入、工具投毒、数据外泄和最小权限'], practice: '把“创建任务”改成两阶段：先生成 canonical payload 和预览，用户确认后执行一次并 read-back。', acceptance: '重试不会重复创建；确认前不产生副作用；审计记录包含可信 actor。', read: '高风险工具必须把授权、确认和执行从模型输出中剥离。' }
    ]
  },
  {
    id: 'm5', label: '05', title: 'Memory、State 与 Context Engineering', time: '第 7 周', color: 'red', description: '让系统在正确的时间拿到正确的信息，而不是把所有历史塞进上下文。',
    lessons: [
      { id: 'm5l1', title: '短期记忆、长期记忆与外部事实', level: '基础', why: '“记住”至少有三种含义，放错存储位置会造成过时信息、隐私问题和上下文膨胀。', learn: ['短期 thread state：当前任务和中间结果', '长期 memory：用户偏好、稳定事实和可更新档案', 'RAG/数据库：可查询的外部事实，不等于聊天记忆', '记忆的来源、置信度、时间、租户和删除策略'], practice: '对 30 条信息做分类：放 message history、checkpoint、long-term memory、RAG 还是业务数据库，并写判断理由。', acceptance: '能解释“用户喜欢简洁回答”和“订单状态是已发货”为什么不能用同一种 memory 处理。', read: '设计 memory schema 时先问生命周期和权威来源。' },
      { id: 'm5l2', title: 'State Schema、Checkpoint 与 Thread', level: '进阶', why: '可恢复 Agent 需要在每个阶段保存可序列化状态，而不是只保存最终回答。', learn: ['state schema、reducer、消息累积与字段更新', 'thread_id、checkpoint、super-step 和恢复点', '状态快照、历史回放和 time travel debugging', '序列化限制、版本迁移和敏感字段处理'], practice: '给一个研究 Graph 设计 State：question、plan、sources、draft、validation、budget；模拟中断后恢复。', acceptance: '中断发生时能知道下一步、已完成副作用和剩余预算。', read: 'LangGraph checkpoint 会在 super-step 边界保存状态。', links: [{ text: 'LangGraph Checkpoints', url: 'https://github.com/langchain-ai/langgraph/tree/main/libs/checkpoint' }] },
      { id: 'm5l3', title: 'Context Engineering：选择、排序、压缩', level: '进阶', why: '模型效果通常由上下文质量决定；上下文工程是对信息流的系统设计。', learn: ['context selection：只放与当前决策有关的信息', 'context ordering：指令、事实、工具结果和历史的优先级', 'summarization、compaction、脱敏和冲突合并', '工具选择、动态加载和最小权限上下文'], practice: '实现 context builder：给定 token budget，优先保留 system、当前目标、未完成任务和证据，裁剪旧消息。', acceptance: '能输出 context manifest，说明每段信息来自哪里、为何被纳入、何时过期。', read: '把 context builder 当作独立模块测试，而不是藏在 Prompt 字符串里。' },
      { id: 'm5l4', title: '记忆写入策略与遗忘', level: '进阶', why: '错误记忆比没有记忆更危险；写入必须有门槛、可解释、可纠正。', learn: ['显式记忆与模型推断记忆', 'importance、confidence、recency 与冲突解决', '用户查看、修改、删除和数据保留期限', '跨用户隔离、PII、权限和审计'], practice: '为“个人助手”设计 memory write policy：只有用户明确表达偏好或确认事实才自动写入。', acceptance: '可以回答每条记忆何时写入、谁能读、如何删除、冲突时谁优先。', read: 'Memory 是产品策略和数据治理问题，不只是向量数据库。' }
    ]
  },
  {
    id: 'm6', label: '06', title: 'LangChain：从抽象到实现', time: '第 8 周', color: 'cyan', description: '掌握模型、消息、工具、Agent 和 middleware 的组合方式，并学会识别抽象边界。',
    lessons: [
      { id: 'm6l1', title: 'LangChain Core：Runnable、Message 与配置', level: '框架', why: 'LangChain 的价值在于统一模型和组件接口；理解 core 才不容易被集成细节绑架。', learn: ['ChatModel、AIMessage、ToolMessage 等消息对象', 'Runnable 的 invoke、batch、stream 和组合思路', 'config、callbacks、metadata、tags 与 tracing', 'provider integration 与能力差异'], practice: '用同一套输入分别调用两个模型适配器，统一输出并记录 metadata；比较 streaming 和 invoke。', acceptance: '能说清楚“接口统一”不等于“模型能力相同”。', read: '源码入口：`langchain-core` 的 messages、runnables 和 callbacks。', links: [{ text: 'LangChain repository', url: 'https://github.com/langchain-ai/langchain' }] },
      { id: 'm6l2', title: 'LangChain Agents 与 create_agent', level: '框架', why: '高层 Agent 可以快速交付，但必须理解它内部仍然是模型—工具循环。', learn: ['model、tools、system_prompt 和 middleware 的组装', '工具调用消息如何进入 Agent 状态', 'structured output、response format 与最终结果', '何时使用高层 Agent，何时下沉到 LangGraph'], practice: '用 `create_agent` 实现一个带查询和确认工具的助手，打开 tracing，标出每个节点。', acceptance: '能把高层 Agent 的行为映射回模型调用、工具调用和图状态。', read: '官方当前推荐从 `create_agent` 开始，而不是照搬旧版 Agent 教程。', links: [{ text: 'LangChain Agents', url: 'https://docs.langchain.com/oss/python/langchain/agents' }] },
      { id: 'm6l3', title: 'Middleware：在 Agent 循环中插入控制点', level: '进阶', why: '可靠性、权限、重试和上下文压缩需要在每轮模型/工具调用前后统一执行。', learn: ['before_model、after_model、before_tool、after_tool hooks', 'PII 检测、模型回退、调用次数限制、工具错误处理', '动态 system prompt 和动态工具选择', 'middleware 与 LangGraph 子图的关系'], practice: '增加三个 middleware：模型调用上限、工具错误转译、PII 脱敏；用失败样例验证 hook 顺序。', acceptance: '能解释某个策略放在 Prompt、middleware、tool wrapper 还是 graph node 的理由。', read: '官方 middleware 文档列出了 retry、fallback、guardrail 和 context control 模式。', links: [{ text: 'LangChain Middleware', url: 'https://docs.langchain.com/oss/python/langchain/middleware' }] },
      { id: 'm6l4', title: 'LangChain RAG 与可观测性', level: '进阶', why: '框架接入 RAG 很快，但生产问题必须能看到检索文档、Prompt、模型和最终引用。', learn: ['Document、Retriever、vector store 和 document chain', 'retrieval trace：query、filters、scores、documents', 'LangSmith trace 的层级、metadata、feedback 和 dataset', '从链路追踪到离线评估和线上监控'], practice: '给 RAG 加 trace metadata：tenant、query_type、retriever_version、top_k；实现一条失败样本回放。', acceptance: '只看 trace 就能判断问题出在切分、检索、Prompt 还是生成。', read: 'LangSmith 是 LangChain 生态中的 tracing/evaluation/deployment 平台。' }
    ]
  },
  {
    id: 'm7', label: '07', title: 'LangGraph：状态图与运行时', time: '第 9–10 周', color: 'blue', description: '从可读的流程图走向可恢复、可中断、可并行的 Agent runtime。',
    lessons: [
      { id: 'm7l1', title: 'StateGraph：State、Node、Edge', level: '框架', why: 'LangGraph 的底层模型很小：共享状态、处理节点、转移边；复杂性来自组合。', learn: ['Typed state schema 与字段 reducer', 'node 是接受 state 并返回 update 的函数', '固定 edge、conditional edge 和 START/END', '节点副作用、纯函数边界和可测试性'], practice: '把“问题分类 → 检索 → 回答”实现成三个节点，先用 mock model 跑通，再接真实模型。', acceptance: '每个 node 都有明确输入输出；graph 在无模型时也能用 fake node 测试。', read: '先读官方 Graph API，再逐步加入 loop 和 persistence。', links: [{ text: 'LangGraph overview', url: 'https://docs.langchain.com/oss/python/langgraph/overview' }] },
      { id: 'm7l2', title: 'Loop、Conditional Routing 与 Command', level: '框架', why: '生产 Agent 需要让“继续/改写/升级人工/结束”成为明确的图转移。', learn: ['条件路由函数和有限状态机思维', 'Command：同时更新状态并跳转', '递归限制、loop invariant 和终止状态', '错误节点、fallback 分支和部分结果'], practice: '实现“检索 → 相关性评估”：相关则回答，不相关则最多改写两次，仍失败转人工。', acceptance: '图上每条边都有触发条件；超过次数后不会回到原路无限循环。', read: '把流程图画出来，检查是否存在不可达节点和无出口循环。' },
      { id: 'm7l3', title: 'Super-step、Pregel 与并行执行', level: '进阶', why: 'LangGraph 不是简单的函数列表；其运行时以消息传递和 super-step 管理节点激活。', learn: ['节点激活、channels、消息传递和 super-step', '并行 fan-out、Send API 与 map-reduce', '并发写同一 state 字段时的 reducer', '顺序一致性、失败传播和重试边界'], practice: '把一个研究问题拆成多个子问题并行检索，再用 reducer 汇总 sources；测试一个子任务失败时的行为。', acceptance: '能解释并行节点为何属于同一 super-step，以及聚合字段为什么需要 reducer。', read: '源码路线：`libs/langgraph/langgraph/pregel` 与 Graph API 的 Send 示例。', links: [{ text: 'LangGraph source', url: 'https://github.com/langchain-ai/langgraph/tree/main/libs/langgraph' }] },
      { id: 'm7l4', title: 'Checkpoint、Interrupt 与 Durable Execution', level: '进阶', why: '长任务、人工审批和故障恢复依赖状态持久化，而不是把整个流程重新跑一遍。', learn: ['checkpoint snapshot、thread_id 与恢复位置', 'interrupt 前保存什么，resume 时提供什么', 'human-in-the-loop 的审批、拒绝和修改状态', '幂等副作用与恢复时的 exactly-once/at-least-once 现实'], practice: '实现“生成工单草稿 → interrupt → 用户确认 → 执行 → read-back”，模拟进程中断后恢复。', acceptance: '恢复不会重复执行已完成副作用；审批记录和最终结果可追溯。', read: '源码路线：`libs/checkpoint`、`libs/prebuilt`，再看 interrupt 示例。', links: [{ text: 'LangGraph checkpoint', url: 'https://github.com/langchain-ai/langgraph/tree/main/libs/checkpoint' }] }
    ]
  },
  {
    id: 'm8', label: '08', title: 'Workflow、Multi-agent 与 Graph Patterns', time: '第 11 周', color: 'green', description: '学习何时拆 Agent，何时用 router、subgraph、handoff 或确定性 workflow。',
    lessons: [
      { id: 'm8l1', title: 'Workflow 与 Agent 的边界', level: '架构', why: '工作流强调可预测路径，Agent 强调模型驱动决策；混用会让系统既不灵活也不可控。', learn: ['确定性 DAG、状态机与 LLM router', '模型适合选择和解释，代码适合校验和副作用', '复杂性、延迟、可测试性和失败面的比较', '从 single-agent 演进到 workflow 的触发信号'], practice: '把一个“报销审核”分别设计成纯 workflow、Agent 和混合 Graph，比较每种方案的风险。', acceptance: '能为每个分支说明为什么由模型判断或由代码判断。', read: '先画业务状态机，再决定哪里嵌入 Agent。' },
      { id: 'm8l2', title: 'Router、Handoff 与 Subgraph', level: '进阶', why: '多 Agent 的关键不是数量，而是上下文和控制权如何转移。', learn: ['router 把请求分发给专长 Agent', 'handoff 把控制权和必要上下文转给另一个 Agent', 'subgraph 封装局部状态和复用复杂能力', '共享上下文、私有上下文与边界转换'], practice: '实现客服 router：订单、物流、退款三个 specialist；规定何时升级人工并保留必要 context。', acceptance: '不会把所有历史和全部工具暴露给每个 Agent；转移原因可解释。', read: '先做一个 Agent + 多工具，再评估是否真的需要多 Agent。' },
      { id: 'm8l3', title: 'Planner/Executor、Reflect 与 Critic', level: '进阶', why: '计划、执行、验证可以提高复杂任务的可控性，但会增加调用和错误传播。', learn: ['planner 输出任务分解与依赖', 'executor 执行单个步骤并回写证据', 'critic 验证目标、格式和证据，不等于重复生成', '动态计划修订、部分完成和预算分配'], practice: '构建研究报告 Graph：plan → 并行 research → synthesis → critic → revise；限制 critic 只允许一次修订。', acceptance: '计划中的每个步骤都有完成判定和证据，不用“看起来完成了”作为结束条件。', read: '把计划当成可执行数据结构，而不是只生成一段自然语言。' },
      { id: 'm8l4', title: '代码执行、MCP 与工具生态', level: '进阶', why: '真实 Agent 常通过工具生态接入数据库、浏览器和内部系统，边界管理比接入本身更重要。', learn: ['code interpreter 与 shell 的能力和风险', 'MCP 的 server、tool、resource、prompt 概念', '工具发现、动态工具集和上下文成本', '沙箱、网络策略、密钥隔离和输出清洗'], practice: '设计一个只读 MCP 工具接入层：列出工具 schema、授权范围、超时、审计字段和失败返回。', acceptance: '能区分工具协议、工具实现、执行沙箱和业务权限四层。', read: '工具生态要从 allowlist、隔离和审计开始。' }
    ]
  },
  {
    id: 'm9', label: '09', title: 'Evaluation、Tracing 与可靠性', time: '第 12 周', color: 'orange', description: '让 Agent 的质量从“感觉不错”变成可以回归、比较和运营的指标。',
    lessons: [
      { id: 'm9l1', title: 'Trace：观察每一轮发生了什么', level: '生产', why: '最终答案无法告诉你 Agent 为什么错；trace 才能还原消息、工具、状态和耗时。', learn: ['trace、run、span、parent/child hierarchy', '输入输出、Prompt、tool args/results、metadata 和 token usage', '敏感信息脱敏与采样', '从 trace 构建失败样本和回放'], practice: '为一次 RAG Agent 画 trace 树，标注模型调用、retrieval、rerank、tool、validation 和最终输出。', acceptance: '能够仅凭 trace 找到一次错误引用的根因。', read: 'LangSmith 和 Langfuse 都可以作为观测平台；关键是事件模型设计。' },
      { id: 'm9l2', title: 'RAG 与 Agent 的评估体系', level: '生产', why: 'Agent 没有一个单一“准确率”；需要把检索、工具、状态、答案和安全拆开测。', learn: ['retrieval recall@k、precision、MRR/nDCG', 'answer correctness、faithfulness、citation completeness', 'tool selection、argument validity、task success', '人工标注、LLM judge、规则检查与抽样复核'], practice: '为毕业项目建立数据集：每条样本包含期望工具、关键事实、禁止动作、参考来源和评分规则。', acceptance: '一次回归能告诉你是 retriever、model、Prompt、tool 或 graph 变化导致退化。', read: '先定义失败类型，再选择指标，避免用一个总分掩盖问题。' },
      { id: 'm9l3', title: '可靠性：重试、回退、超时与降级', level: '生产', why: '线上失败来自模型、网络、供应商、工具和数据；每一类失败的恢复策略不同。', learn: ['瞬时错误与永久错误', '指数退避、jitter、retry budget 和熔断', 'fallback model、fallback workflow 和人工升级', '缓存、幂等键、deadline 和部分结果'], practice: '给工具和模型注入超时、429、5xx、空结果和错误 schema，验证每条路径。', acceptance: '能画出 failure matrix，并说明每个错误是否重试、替代、询问还是终止。', read: '不要用无限重试掩盖不可恢复的业务错误。' },
      { id: 'm9l4', title: '安全、权限与 Prompt Injection', level: '生产', why: 'RAG 文档、网页和工具结果都可能包含不可信指令；Agent 必须把数据和指令分离。', learn: ['直接/间接 Prompt Injection', '系统指令、用户输入、检索数据和工具结果的信任等级', '最小权限、租户隔离、PII/secret redaction', '高风险动作确认、审计、速率限制和数据外泄防护'], practice: '构造含恶意指令的网页和文档，验证 Agent 不会把检索内容当成系统命令，也不会泄露秘密。', acceptance: '所有 write tool 都有服务端授权和确认；安全失败会停止或升级，而不是继续猜。', read: '安全策略必须落实在执行边界，不能只写一句“不要被提示注入”。' }
    ]
  },
  {
    id: 'm10', label: '10', title: '部署、性能与数据工程', time: '第 13–14 周', color: 'red', description: '从本地 Demo 走到有并发、可观测、可升级的数据服务。',
    lessons: [
      { id: 'm10l1', title: '服务化与流式交互', level: '生产', why: 'Agent 通常是长请求；用户体验和服务稳定性都依赖流式状态设计。', learn: ['同步 invoke、token stream、event stream 和状态 stream', 'SSE/WebSocket 的断线、重连和 replay', '首 token 延迟、工具等待和最终完成时间', '客户端展示中间状态而不是暴露不可理解的内部推理'], practice: '把研究 Agent 改成事件流：发送节点开始/结束、工具调用、引用和最终报告；支持断线后按 run_id 恢复。', acceptance: '用户能知道当前阶段；重连不会重复渲染或重复执行工具。', read: '流式协议要定义事件类型、顺序、ID、完成和错误语义。' },
      { id: 'm10l2', title: '并发、队列与资源预算', level: '生产', why: '多用户、多 Agent 和并行检索会放大模型、数据库和工具的资源压力。', learn: ['并发模型、任务队列、backpressure 和取消', 'per-user/per-tenant rate limit', '模型并发、连接池、向量库和缓存', '预算分配：请求、用户、租户和全局'], practice: '为并行研究设计 worker pool：限制每个任务的并发子问题数，并在 deadline 到达时取消未完成工作。', acceptance: '高负载下系统仍能拒绝、降级或排队，而不是无限堆积。', read: '把模型调用视为远程资源，把工具执行视为有副作用的任务。' },
      { id: 'm10l3', title: '索引更新、版本与数据权限', level: '生产', why: '企业知识会更新、删除和改变权限；RAG 不能只有一次性 ingest 脚本。', learn: ['文档版本、增量索引、删除 tombstone 和重建', 'embedding/index/retriever 版本绑定', 'metadata filter 与权限继承', '缓存失效、旧答案和时间有效性'], practice: '实现文档更新流程：同一 source 更新后旧 chunk 失效，新版本可检索，权限变化即时生效。', acceptance: '能回答“这条答案基于哪个版本、谁有权看到、文档删除后何时不再返回”。', read: '把 source of truth、index state 和 answer citation 串起来。' },
      { id: 'm10l4', title: '成本、延迟与质量的三角权衡', level: '生产', why: '“更强模型 + 更多检索 + 更多自检”通常能提高质量，但也会提高成本和延迟。', learn: ['模型调用次数、输入输出 token、工具费用', '粗粒度缓存、语义缓存和结果缓存的风险', '小模型路由、早停和动态 top-k', '质量-成本-延迟的分层目标'], practice: '为同一任务设计 cheap、balanced、high-quality 三档策略，比较 P50/P95 延迟、成本和质量。', acceptance: '能用数据解释一次优化为什么值得，而不是只比较单次耗时。', read: '优化前先观测完整链路，避免只优化模型调用而忽略检索和工具。' }
    ]
  },
  {
    id: 'm11', label: '11', title: '优秀开源项目源码导读', time: '第 15–16 周', color: 'ink', description: '通过源码理解不同框架如何组织数据、流程、运行时和扩展点。',
    lessons: [
      { id: 'm11l1', title: 'LangChain：组件抽象与 Agent 工厂', level: '源码', why: 'LangChain 适合快速组合模型和工具；源码阅读重点是接口、middleware 和 Agent 构造。', learn: ['`langchain-core`：messages、runnables、callbacks、tools', '`libs/langchain_v1/langchain/agents`：Agent API、middleware 和 state', 'provider adapter 如何把统一消息映射到供应商协议', '哪些对象是公共契约，哪些只是实现便利'], practice: '从 `create_agent` 追踪到模型节点和工具节点，画出状态更新和 middleware hook 顺序。', acceptance: '能用一个简化版 Python 实现复刻 Agent 的核心控制流。', read: '源码入口建议：`langchain/libs/langchain_v1`、`langchain/libs/core`。', links: [{ text: 'langchain-ai/langchain', url: 'https://github.com/langchain-ai/langchain' }] },
      { id: 'm11l2', title: 'LangGraph：Pregel、Checkpoint 与可恢复执行', level: '源码', why: 'LangGraph 的差异化在 runtime；理解 Pregel/super-step/checkpoint 才能正确设计恢复和并行。', learn: ['StateGraph 编译为可执行图的过程', '`langgraph/pregel` 的任务调度、channels 和写入', '`libs/checkpoint` 的 checkpoint tuple、serde 和 storage protocol', 'interrupt、resume、subgraph snapshot 与 time travel'], practice: '阅读一个最小图的执行路径，记录每个 super-step 的 state snapshot 和 pending tasks。', acceptance: '能解释某个节点失败后哪些写入已持久化，以及恢复会从哪里继续。', read: '源码入口：`langgraph/libs/langgraph`、`langgraph/libs/checkpoint`。', links: [{ text: 'langchain-ai/langgraph', url: 'https://github.com/langchain-ai/langgraph' }] },
      { id: 'm11l3', title: 'LlamaIndex：文档数据到 Agent Workflow', level: '源码', why: 'LlamaIndex 强项是数据接入、索引、查询和工作流；适合对比“data framework”与“runtime framework”。', learn: ['Document、Node、Index、Retriever、Query Engine 的数据流', '存储上下文、持久化索引和 metadata filter', '`AgentWorkflow`、FunctionAgent 与 handoff', 'Agentic RAG 和 Workflows 如何把数据能力交给 Agent'], practice: '用同一份文档分别实现 VectorStoreIndex 查询和 AgentWorkflow 工具查询，比较控制权和可观测性。', acceptance: '能说明 LlamaIndex 在数据层的优势，以及何时需要额外的图运行时。', read: '源码入口：`llama-index-core/llama_index/core`，重点看 agent/workflow、indices、retrievers。', links: [{ text: 'run-llama/llama_index', url: 'https://github.com/run-llama/llama_index' }] },
      { id: 'm11l4', title: 'Haystack：Component Graph 与 Agent State', level: '源码', why: 'Haystack 把可序列化组件和 pipeline graph 作为核心，适合比较确定性 pipeline 与 Agent loop。', learn: ['Component 输入输出 socket 和 pipeline execution graph', '连接验证、拓扑排序、组件最大运行次数', 'Agent state_schema、Toolset、PipelineTool 与 human-in-the-loop', '如何把整个 pipeline 封装为 Agent tool'], practice: '阅读 PipelineBase 的执行调度逻辑，构建一个带 max_runs_per_component 的循环 pipeline。', acceptance: '能说清 pipeline graph 的确定性调度与 Agent 的模型驱动工具选择有什么不同。', read: '源码入口：`haystack/core/pipeline/base.py`、Agent component 文档。', links: [{ text: 'deepset-ai/haystack', url: 'https://github.com/deepset-ai/haystack' }] }
    ]
  },
  {
    id: 'm12', label: '12', title: '毕业项目：企业知识与工单助手', time: '第 17–20 周', color: 'yellow', description: '把前面的知识整合成一个有真实边界、可验证、可演示的系统。',
    lessons: [
      { id: 'm12l1', title: '需求、威胁模型与架构设计', level: '项目', why: '毕业项目先写边界和失败策略，再写 Agent；否则很容易变成无边界 Demo。', learn: ['用户角色、资源、权限和业务动作', 'read / write / confirm / audit 的能力分级', '数据流、信任边界和外部副作用', '成功、部分成功、拒绝、升级人工和失败状态'], practice: '产出一页架构图和 threat model：标出模型、检索、工具、数据库、审批和观测边界。', acceptance: '每个功能都有 owner、数据来源、失败路径和验收指标。', read: '先定义 contract，再选框架。' },
      { id: 'm12l2', title: '实现 RAG 与工具能力', level: '项目', why: '先把可验证的确定性能力做稳，再让 Agent 负责路由和组合。', learn: ['文档 ingest/index/retrieval pipeline', '来源引用、权限过滤和无证据拒答', 'SQL read-only tool 与任务查询 tool', '统一 error envelope、timeout 和 trace metadata'], practice: '完成知识问答、项目查询、SQL 查询三个能力，并为每个能力写离线测试集。', acceptance: 'Agent 不调用不必要的工具；每个答案或查询结果有来源和权限依据。', read: '把工具当作独立服务测试，再接入 Agent。' },
      { id: 'm12l3', title: 'LangGraph 编排与人工确认', level: '项目', why: '把高风险写入放进可中断图中，练习状态、checkpoint、审批和 read-back。', learn: ['意图路由、RAG subgraph、SQL subgraph、write approval subgraph', 'canonicalize → classify → confirm → execute → read-back → receipt', 'checkpoint、interrupt、resume 和幂等键', 'streaming event 与前端状态展示'], practice: '实现创建任务流程：模型提取字段 → 代码校验 → 展示预览 → 用户确认 → 执行一次 → 读取结果。', acceptance: '没有确认不会写入；断线重连不会重复执行；最终返回可审计 receipt。', read: '这是整个课程最重要的工程闭环。' },
      { id: 'm12l4', title: '质量门禁、复盘与开源发布', level: '项目', why: '掌握的标准是别人能运行、理解和验证，而不是本地演示成功。', learn: ['单元测试、contract test、graph path test、eval dataset', 'trace review、成本/延迟报表和回归门禁', 'README、架构图、威胁模型、运行手册和 demo', '把一个通用组件抽成可复用开源项目'], practice: '录制一次完整演示，提交 50 条评估样例、10 条攻击样例、失败复盘和下一阶段 TODO。', acceptance: '陌生开发者能按 README 跑起来；你能解释每个已知限制和未解决风险。', read: '用“可运行、可测量、可恢复、可解释”作为毕业标准。' }
    ]
  }
];

const SOURCE_GUIDE = [
  { name: 'LangChain', focus: '组件抽象、Agent、middleware、provider integrations', url: 'https://github.com/langchain-ai/langchain' },
  { name: 'LangGraph', focus: 'StateGraph、Pregel runtime、checkpoint、interrupt', url: 'https://github.com/langchain-ai/langgraph' },
  { name: 'LlamaIndex', focus: '数据接入、索引、Retriever、AgentWorkflow', url: 'https://github.com/run-llama/llama_index' },
  { name: 'Haystack', focus: 'Component pipeline、Agent state、可序列化执行', url: 'https://github.com/deepset-ai/haystack' },
  { name: 'DSPy', focus: '声明式模块、optimizers、评估驱动 Prompt 编译', url: 'https://github.com/stanfordnlp/dspy' },
  { name: 'AutoGen', focus: '多 Agent 对话、event-driven runtime、协作模式', url: 'https://github.com/microsoft/autogen' },
  { name: 'Chroma / pgvector', focus: '向量存储、metadata filter、索引与持久化', url: 'https://github.com/chroma-core/chroma' },
  { name: 'Langfuse', focus: 'LLM tracing、评估、Prompt 与成本观测', url: 'https://github.com/langfuse/langfuse' }
];
