const LABS = [
  { id: 'model-budget', number: '01', title: '上下文预算器', chapter: '01 模型基础', path: 'labs/01-model-and-protocol', goal: '把“上下文有限”变成一个可证明的装箱问题：为输出和工具回合预留空间，再按可信度和重要性选择输入。', concepts: ['Tokenization', 'Context window', 'Prompt caching'], commands: ['python3 -m unittest labs/01-model-and-protocol/test_token_budget.py -v'], checks: ['永不超出窗口', '系统策略和最近用户目标不会被静默删除', '每次裁剪均有原因记录'], source: '01-model-and-protocol/README.md' },
  { id: 'structured-contract', number: '02', title: '结构化输出与业务校验', chapter: '02 Prompt 协议', path: 'labs/02-structured-output', goal: '区分 JSON 能解析、字段满足 schema、业务语义合法三层；模型只负责提议，代码负责裁决。', concepts: ['JSON Schema', 'Tool calling', 'Semantic validation'], commands: ['python3 -m unittest labs/02-structured-output/test_contract.py -v'], checks: ['拒绝未知字段和类型漂移', '拒绝无效日期/越权状态迁移', '保存可解释的校验错误'], source: '02-structured-output/README.md' },
  { id: 'rag-retrieval', number: '03', title: '从零实现混合检索', chapter: '03 RAG', path: 'labs/03-rag-from-scratch', goal: '实现 lexical + semantic 的候选集合与 RRF 融合，理解召回、排序、证据打包各自的责任。', concepts: ['Chunking', 'Hybrid retrieval', 'RRF', 'Reranking'], commands: ['python3 -m unittest labs/03-rag-from-scratch/test_hybrid_retrieval.py -v'], checks: ['两个召回器的分数不直接相加', 'RRF 对排名而不是分值融合', '答案附带被使用的 source id'], source: '03-rag-from-scratch/README.md' },
  { id: 'agent-loop', number: '04', title: '最小可控 Agent Loop', chapter: '04 Agent Runtime', path: 'labs/04-native-agent-loop', goal: '用确定性 fake model 和工具实现 Observe → Decide → Authorize → Act → Record，并把停止条件与写操作确认写进 runtime。', concepts: ['Agent loop', 'Tool protocol', 'Authorization', 'Event log'], commands: ['python3 -m unittest labs/04-native-agent-loop/test_runtime.py -v'], checks: ['写工具未经确认不能执行', '超过步数后稳定停止', '每一个工具结果都能被事件日志还原'], source: '04-native-agent-loop/README.md' },
  { id: 'context-builder', number: '05', title: '上下文编译器', chapter: '05 Context Engineering', path: 'labs/05-context-builder', goal: '将 trusted policy、用户任务、检索证据、工具输出分区并按预算装配，避免把不可信数据升级为指令。', concepts: ['Context engineering', 'Prompt injection', 'Provenance'], commands: ['python3 -m unittest labs/05-context-builder/test_context_builder.py -v'], checks: ['每个片段带 source 与 trust 标签', '不可信工具输出不进入系统指令区', '输出包含装配清单'], source: '05-context-builder/README.md' },
  { id: 'memory-store', number: '06', title: '记忆写入策略', chapter: '06 Memory', path: 'labs/06-memory-system', goal: '实现带来源、置信度、TTL 与冲突处理的 memory store；理解“能检索”不等于“应该写入”。', concepts: ['Memory', 'Provenance', 'Consolidation', 'TTL'], commands: ['python3 -m unittest labs/06-memory-system/test_memory.py -v'], checks: ['低可信内容不能覆盖用户确认事实', '过期记忆不可被召回', '每次更新保留原因与版本'], source: '06-memory-system/README.md' },
  { id: 'graph-checkpoint', number: '07', title: '图状态与 Checkpoint', chapter: '08 LangGraph', path: 'labs/07-graph-checkpoint', goal: '构建小型状态图，在副作用前写 checkpoint，并在恢复时使用幂等键避免重复提交。', concepts: ['State graph', 'Checkpoint', 'Idempotency', 'Interrupt'], commands: ['python3 -m unittest labs/07-graph-checkpoint/test_graph_state.py -v'], checks: ['恢复不重复调用外部写操作', '每次转移都有 state snapshot', '中断值从 checkpoint 恢复'], source: '07-graph-checkpoint/README.md' },
  { id: 'multi-agent', number: '08', title: '多 Agent 委派协议', chapter: '09 Multi-agent', path: 'labs/08-multi-agent', goal: '让 coordinator 只交付类型化任务包和预算；worker 返回 artifact，而不是互相堆叠聊天历史。', concepts: ['Delegation', 'Artifact', 'Budget', 'A2A'], commands: ['python3 -m unittest labs/08-multi-agent/test_orchestrator.py -v'], checks: ['任务输入、输出、预算可审计', 'worker 不能取得未授权工具', '协调者可拒绝不完整 artifact'], source: '08-multi-agent/README.md' },
  { id: 'agent-evals', number: '09', title: 'Agent Eval Harness', chapter: '10 评估与可观测性', path: 'labs/09-agent-evals', goal: '以 task、trial、grader、transcript、outcome 定义评测，避免只评最终自然语言。', concepts: ['Evals', 'Trace', 'Grader', 'Regression'], commands: ['python3 -m unittest labs/09-agent-evals/test_harness.py -v'], checks: ['同时评价结果与过程约束', '失败保留完整 transcript', '可生成稳定回归报告'], source: '09-agent-evals/README.md' },
  { id: 'production-runtime', number: '10', title: '长期运行与可靠交付', chapter: '11 生产系统', path: 'labs/10-production-agent', goal: '实现 lease、heartbeat、cancel、retry 与 outbox 的最小模型；区分 at-least-once 与 exactly-once 的工程边界。', concepts: ['Queue', 'Lease', 'Heartbeat', 'Saga', 'SLO'], commands: ['python3 -m unittest labs/10-production-agent/test_event_log.py -v'], checks: ['超时 lease 能安全重领', '取消会阻止后续行动', '外部副作用由 outbox 和幂等键保护'], source: '10-production-agent/README.md' }
  ,{ id: 'provider-adapter', number: '11', title: '真实模型 Provider 适配层', chapter: '12 Capstone', path: 'labs/11-provider-adapter', goal: '用统一的 Message/ToolCall contract 包住不同模型供应商，处理超时、重试、流式事件和 schema 版本，而不让 provider 差异污染 Agent Runtime。', concepts: ['Provider adapter', 'Streaming', 'Retry budget', 'Contract test'], commands: ['python3 -m unittest labs/11-provider-adapter/test_adapter.py -v'], checks: ['provider 原始响应被归一化为统一事件', '只对明确的 transient error 重试', 'tool_call id 和参数在流式/非流式路径一致'], source: '11-provider-adapter/README.md' }
  ,{ id: 'sqlite-vector-store', number: '12', title: '可持久化的向量索引', chapter: '03 RAG', path: 'labs/12-sqlite-vector-store', goal: '使用 SQLite BLOB 持久化 embedding，完成余弦检索、tenant 过滤、删除传播和重建索引；理解“向量库”本质上是索引与一致性协议。', concepts: ['Embedding', 'SQLite', 'Cosine similarity', 'Delete propagation'], commands: ['python3 -m unittest labs/12-sqlite-vector-store/test_vector_store.py -v'], checks: ['重启后数据仍可检索', 'tenant 过滤先于相似度排序', '删除后不能被召回', '维度不一致会明确失败'], source: '12-sqlite-vector-store/README.md' }
  ,{ id: 'mcp-server', number: '13', title: '从零实现 MCP Server', chapter: '12 Capstone', path: 'labs/13-mcp-server', goal: '实现 MCP initialize、tools/list、tools/call 的最小 JSON-RPC server，并把能力协商、参数校验、授权和错误映射分开。', concepts: ['MCP', 'JSON-RPC', 'Capability negotiation', 'Tool authorization'], commands: ['python3 -m unittest labs/13-mcp-server/test_server.py -v'], checks: ['initialize 前拒绝工具调用', 'tools/list 不等于授权通过', '未知工具/坏参数返回结构化错误', '每次调用都有 request id 和审计事件'], source: '13-mcp-server/README.md' }
  ,{ id: 'capstone-agent', number: '14', title: '项目管理 Agent Capstone', chapter: '12 Capstone', path: 'labs/14-capstone', goal: '把模型、检索、工具、记忆、图状态、审批、评测和观测串成一个可恢复的项目管理助手，完成从任务读取到安全写回的闭环。', concepts: ['End-to-end Agent', 'Policy gate', 'Checkpoint', 'Evals', 'OpenTelemetry'], commands: ['python3 -m unittest labs/14-capstone/test_capstone.py -v'], checks: ['读请求可自动完成，写请求必须审批', '证据不足时拒绝猜测', '中断恢复不重复写入', 'trace 可还原每次决策与成本', '回归评测报告可重复生成'], source: '14-capstone/README.md' }
];

const LAB_BY_ID = Object.fromEntries(LABS.map(lab => [lab.id, lab]));
