const p = (id, name, category, status, positioning, architecture, modules, flow, decisions, limits, improve, relations, sources) => ({ id, name, category, status, positioning, architecture, modules, flow, decisions, limits, improve, relations, sources });

const PROJECT_CASES = [
  p('langchain', 'LangChain', 'Agent Framework', '开源 · Python/TypeScript', `面向应用开发的高层 Agent 框架：统一模型、消息、工具、structured output 和 middleware，并使用 LangGraph 作为 Agent runtime。`, `flowchart LR\n  App[Application] --> CA[create_agent]\n  CA --> MW[Middleware stack]\n  MW --> MN[Model node]\n  MN -->|tool calls| TN[Tool node]\n  TN --> MN\n  CA --> LG[Compiled LangGraph]`, [
    { name: 'langchain-core/messages', what: '规范化 Human/AI/System/Tool 消息和 content blocks。', how: 'provider translator 将内部消息转换成供应商协议。', why: '应用不直接耦合每家模型的消息格式。' },
    { name: 'langchain-core/runnables', what: '统一 invoke、batch、stream、retry、fallback 与组合接口。', how: 'RunnableConfig 传播 callbacks、metadata、tags 和并发配置。', why: '让模型、Retriever、函数和 Graph 可以按相同方式组合。' },
    { name: 'langchain-core/tools', what: '定义 BaseTool/StructuredTool 与参数 schema。', how: '从函数签名/Pydantic 生成工具描述和校验逻辑。', why: '把模型的行动意图限制在类型化 API。' },
    { name: 'langchain/agents/factory.py', what: '构造 create_agent 的模型节点、工具节点、边和状态。', how: '把 middleware hooks 注入模型与工具调用前后，再编译成 LangGraph。', why: '提供少量代码即可使用的预制 Agent loop。' },
    { name: 'langchain/agents/middleware', what: '模型重试、fallback、调用限制、PII、HITL、摘要等横切策略。', how: 'hooks 包围 model/tool 执行，修改 request、state 或结果。', why: '避免每个 Agent 重复实现运行时治理。' }
  ], ['应用调用 create_agent 返回的 compiled graph', 'model node 编译 Prompt、消息和工具 schema', '模型返回 final 或 tool_calls', 'tool node 校验和执行，再产生 ToolMessage', 'middleware 在每轮插入预算、重试、HITL 等策略'], ['高层 API 优先优化开发速度和 provider 可替换性。', 'Agent 构建在 LangGraph 上，因此基本 Agent 不要求用户直接写图，复杂控制时仍可下沉。'], ['抽象层多，排查时必须沿 Runnable/Graph/Provider adapter 追踪。', '统一接口不能消除模型能力差异；旧版教程 API 变化快。'], ['先掌握 core 消息与工具协议，再读 factory；为版本升级建立 contract tests。'], `LangChain 是“组件与预制 Agent”，LangGraph 是“低层编排 runtime”；两者互补，不是竞争替代。`, [{ label: 'Repository', url: 'https://github.com/langchain-ai/langchain' }, { label: 'Agents docs', url: 'https://docs.langchain.com/oss/python/langchain/agents' }]),

  p('langgraph', 'LangGraph', 'Graph Runtime', '开源 · Python/TypeScript', `低层、有状态、可持久化的 Agent 编排运行时，重点是 StateGraph、Pregel 执行、checkpoint、interrupt、streaming 与 durable execution。`, `flowchart TB\n  SG[StateGraph builder] --> CG[Compiled graph]\n  CG --> PR[Pregel runtime]\n  PR --> CH[Channels + reducers]\n  PR --> TK[Tasks / super-steps]\n  TK --> CP[Checkpointer]\n  TK --> IN[Interrupt / resume]\n  PR --> ST[Streaming events]`, [
    { name: 'langgraph/graph', what: 'StateGraph、MessagesState、START/END 和图编译。', how: '收集 nodes、edges、branches 和 schema，编译为可执行 Pregel。', why: '用声明式拓扑表达状态转移。' },
    { name: 'langgraph/pregel', what: '核心执行器、loop、task、runner 和 channel 管理。', how: '按 super-step 调度活跃节点，合并 writes，生成下一批 task。', why: '支持并行、循环和可恢复执行，而不只是顺序函数链。' },
    { name: 'libs/checkpoint', what: 'checkpoint/store/serde 协议及内存、SQLite、Postgres 实现。', how: '保存 state snapshot、config、metadata、pending writes。', why: '为 thread、HITL、失败恢复和 time travel 提供持久化。' },
    { name: 'libs/prebuilt', what: 'ToolNode、验证节点和常用 Agent 组件。', how: '把消息中的 tool_calls 映射到并发工具执行并配对 ToolMessage。', why: '复用常见 Agent loop 组件但保留 Graph 控制。' },
    { name: 'stream / interrupt', what: '事件流和暂停恢复 API。', how: '按 messages/updates/custom 等模式发事件；interrupt 将恢复值写回 task。', why: '支持长任务 UI、人工审批和调试。' }
  ], ['输入写入初始 channels 并建立 checkpoint', 'Pregel loop 计算当前 super-step 的活跃 tasks', 'Runner 执行节点，节点产生 writes 或 interrupt', 'barrier 合并 writes/reducers 并保存 checkpoint', '产生下一 step；无任务则完成，interrupt 则等待 resume'], ['将状态和控制流显式化，优先可恢复和可观察。', 'Pregel 模型使并行节点读取稳定快照，避免同一步内隐式竞态。'], ['需要设计 state schema/reducer；错误图可能出现复杂循环。', 'checkpoint 不自动保证外部系统 exactly-once，副作用仍需幂等。'], ['节点保持小而确定；状态大对象外置；用路径测试和 checkpoint conformance test。'], `LangChain create_agent 编译成 LangGraph；也可不使用 LangChain，直接在 LangGraph 节点中调用任意模型/代码。`, [{ label: 'Repository', url: 'https://github.com/langchain-ai/langgraph' }, { label: 'Graph API', url: 'https://docs.langchain.com/oss/python/langgraph/graph-api' }, { label: 'Checkpoint source', url: 'https://github.com/langchain-ai/langgraph/tree/main/libs/checkpoint' }]),

  p('llamaindex', 'LlamaIndex', 'RAG / Data Framework', '开源 · Python/TypeScript', `以文档数据接入、Node/Index、Retriever、Query Engine 和 AgentWorkflow 为核心的数据框架，擅长构建 RAG 与文档 Agent。`, `flowchart LR\n  DS[Data sources] --> Reader\n  Reader --> Doc[Documents]\n  Doc --> Parse[Node parser]\n  Parse --> IDX[Index / vector store]\n  Q[Query] --> Ret[Retriever]\n  IDX --> Ret\n  Ret --> QE[Query engine]\n  QE --> Synth[Response synthesizer]\n  WF[AgentWorkflow] --> QE`, [
    { name: 'Schema: Document/Node', what: '承载文本、关系、metadata 和来源的基本数据对象。', how: 'Document 通过 parser 变成可索引 nodes，保留 source relationships。', why: '把数据血缘带入 retrieval/query。' },
    { name: 'Readers / IngestionPipeline', what: '加载数据并执行转换。', how: '串联 parser、metadata extractor、embedding；支持缓存和增量策略。', why: '把离线 ingest 从在线查询分离。' },
    { name: 'Index / StorageContext', what: '管理 docstore、index store、vector store。', how: '索引结构引用 nodes，storage context 抽象持久化后端。', why: '允许替换向量库并持久化数据层。' },
    { name: 'Retriever / QueryEngine', what: '召回候选并组织生成。', how: 'Retriever 返回 NodeWithScore，QueryEngine 接入 postprocessors 和 response synthesizer。', why: '分离召回、后处理和生成。' },
    { name: 'Workflows / AgentWorkflow', what: '事件驱动步骤与 Agent handoff。', how: 'step 接收/产生 events，context/state 跨步骤共享。', why: '在数据能力之上支持 Agentic RAG。' }
  ], ['Reader 加载 source 形成 Documents', 'Node parser 切分并保留关系与 metadata', 'Embedding/index 写入 storage context', 'Retriever 根据 query 返回带 score 的 nodes', 'postprocessor/reranker 处理后交给 synthesizer 或 Agent 工具'], ['从“数据如何进入 LLM 应用”出发，抽象比纯 Agent runtime 更偏数据层。'], ['高层 API 方便但默认策略容易被忽略；复杂 workflow 的 runtime 能力需和 LangGraph/Haystack 比较。'], ['显式版本化 ingest；对 Node/score/source 做 trace；先掌握低层 retriever/query engine。'], `与 LangChain 可互相集成；相较 LangGraph，LlamaIndex 更强调数据和检索抽象，LangGraph更强调执行状态。`, [{ label: 'Repository', url: 'https://github.com/run-llama/llama_index' }, { label: 'Docs', url: 'https://docs.llamaindex.ai/' }]),

  p('haystack', 'Haystack', 'RAG / Pipeline Framework', '开源 · Python', `以 typed Components 和有向 Pipeline 为核心的 RAG/Agent 框架，强调组件输入输出、连接校验和可序列化执行图。`, `flowchart LR\n  Input --> C1[Component]\n  C1 --> C2[Retriever]\n  C2 --> C3[Ranker]\n  C3 --> C4[Generator]\n  Agent --> PT[PipelineTool]\n  PT --> C1`, [
    { name: 'Component', what: '声明输入/输出 socket 的处理单元。', how: '装饰器和类型信息定义 contract，run 返回命名输出。', why: '在连接 Graph 前验证类型和必填输入。' },
    { name: 'PipelineBase', what: '组件编排、连接验证和执行图基础。', how: 'FIFO priority queue 根据输入就绪状态调度组件，限制 max_runs_per_component。', why: '支持分支和循环同时防止无限运行。' },
    { name: 'DocumentStore / Retriever', what: '存储与召回文档。', how: '按 backend 提供 BM25、embedding 和 filter 组件。', why: '检索后端与 Pipeline 逻辑解耦。' },
    { name: 'Agent + State', what: '维护 tool-calling loop 和 typed state。', how: 'ChatGenerator 产生 tool calls，ToolInvoker 执行，state_schema 合并工具状态。', why: '把 Agent 放入已有组件生态。' },
    { name: 'ComponentTool/PipelineTool', what: '把组件或整条 Pipeline 暴露为工具。', how: '从 component sockets 生成 schema 并映射输入输出。', why: '复用确定性 RAG Pipeline 作为 Agent 能力。' }
  ], ['Pipeline 接收初始 inputs', '调度器判断 component 是否 ready/defer/blocked', '组件 run 产生输出并路由到下游 socket', '循环组件受最大运行次数保护', 'Agent 可把 Pipeline 包装为单个 tool 调用'], ['类型化组件和显式连接适合可维护的 RAG pipeline。', 'PipelineTool 体现“确定性能力封装后交给 Agent”的分层。'], ['复杂 Pipeline 调试需要理解调度队列；集成包拆分较多。'], ['保持组件单一职责；为 socket contract 和 serialization 写测试；Agent loop 单独设预算。'], `与 LlamaIndex 都强于数据/RAG；Haystack更偏组件 DAG，LlamaIndex更偏文档 Index/QueryEngine。`, [{ label: 'Repository', url: 'https://github.com/deepset-ai/haystack' }, { label: 'Pipeline source', url: 'https://github.com/deepset-ai/haystack/blob/main/haystack/core/pipeline/base.py' }]),

  p('mem0', 'Mem0', 'AI Memory', '开源 · Python/TypeScript', `通用 Agent 长期记忆层：从对话中抽取候选事实，决定新增/更新/删除/忽略，写入向量存储并按用户检索。`, `flowchart LR\n  Msg[Messages] --> Extract[LLM fact extraction]\n  Extract --> Decide[ADD/UPDATE/DELETE/NOOP]\n  Decide --> VS[(Vector store)]\n  Decide --> GH[(Optional graph)]\n  Q[Query + user] --> Search[Similarity + filters]\n  VS --> Search\n  Search --> Context`, [
    { name: 'mem0/memory/main.py', what: 'Memory 的 add/search/update/delete 主流程。', how: '协调 LLM、embedding、vector store、history 和可选 graph store。', why: '提供统一记忆 API。' },
    { name: 'configs/prompts.py', what: '事实抽取和记忆更新决策 Prompt。', how: '先从对话抽取事实，再与已有近邻记忆比较，输出操作。', why: '减少把整段聊天直接存储造成的噪音。' },
    { name: 'vector_stores adapters', what: 'Chroma、Qdrant、pgvector 等后端。', how: '统一插入、检索、过滤和删除接口。', why: '让记忆存储可部署在不同基础设施。' },
    { name: 'LLM / Embedder adapters', what: '模型与 embedding provider 配置。', how: 'factory 根据配置构建 provider 实现。', why: '提取/检索不绑定单一模型。' },
    { name: 'history / telemetry', what: '记录记忆变更和系统行为。', how: '保存 operation 历史及匿名使用事件。', why: '支持调试更新过程。' }
  ], ['add 接收 messages 与 user/agent/run scope', 'LLM 提取可长期保存的原子事实', '向量搜索找现有相似记忆', 'LLM/规则决定 ADD、UPDATE、DELETE、NOOP', '写入后 search 按 query、scope 和 filter 召回'], ['把记忆视为独立服务，方便嵌入任意 Agent。', '两阶段提取/决策比直接保存摘要更能处理更新与去重。'], ['LLM 写入决策可能误删/误并；向量相似难处理时间和否定；安全依赖调用方正确传 scope。'], ['增加 provenance、有效期、确定性冲突规则、可逆更新和 memory eval。'], `可作为 LangGraph/CrewAI 等 Agent 的外置长期记忆；与 Letta 的“Agent 自管理上下文”定位不同。`, [{ label: 'Repository', url: 'https://github.com/mem0ai/mem0' }, { label: 'Paper', url: 'https://arxiv.org/abs/2504.19413' }]),

  p('letta', 'Letta / MemGPT', 'Stateful Agent / Memory', '开源核心持续演进', `把 LLM 当作有有限主存和外部存储的“操作系统进程”：Agent 能通过工具读写 core memory、recall/archival memory，并管理自己的上下文。`, `flowchart TB\n  SP[System prompt] --> CM[Core memory blocks]\n  CM --> CW[Context window]\n  RM[(Recall memory)] --> MT[Memory tools]\n  AM[(Archival / MemFS)] --> MT\n  MT --> CW\n  CW --> LLM\n  LLM --> MT`, [
    { name: 'Core memory blocks', what: '始终在上下文中的 persona、human 或自定义 blocks。', how: '按 label/limit 渲染成结构化 Prompt，并提供 edit tools。', why: '让关键身份和用户信息稳定可见。' },
    { name: 'Recall memory', what: '过去消息和事件。', how: '按时间或查询读取会话历史。', why: '在有限窗口外保留对话经历。' },
    { name: 'Archival memory / MemFS', what: '长文档与长期知识。', how: '旧实现用 archival rows；当前 MemFS 使用 Git-backed Markdown，system/ 常驻、其他文件按需读取。', why: '把大量知识移出常驻上下文并保留可编辑/版本化结构。' },
    { name: 'Context manager', what: '计算 token、编译 system/memory/messages。', how: '根据限制决定何时总结或分页外部 memory。', why: '显式管理有限 context window。' },
    { name: 'Memory tools', what: '让 Agent 自己 insert/replace/search memory。', how: '工具调用改变 blocks 或外部存储，下一轮反映到上下文。', why: '把记忆管理纳入 Agent 行动。' }
  ], ['构建 system prompt 与 core memory', '加载窗口内消息和外部 memory summary', '模型决定回答、调用业务工具或 memory tool', 'memory tool 修改持久状态', 'context manager 在后续轮次重新编译上下文'], ['从虚拟内存得到类比：重要数据常驻，更多数据分页到外部。', '可编辑 memory 让 Agent 主动整理，而不是被动检索全部历史。'], ['Agent 可能错误修改自己的记忆；常驻 blocks 有 token 成本；新旧仓库/架构正在演进。'], ['Git 版本、权限、memory validator、用户审计；固定当前源码版本再做实现分析。'], `Mem0 是可插拔 memory service；Letta 是以 memory/context management 为中心的完整 stateful agent runtime。`, [{ label: 'Current Letta repository', url: 'https://github.com/letta-ai/letta-code' }, { label: 'MemGPT paper', url: 'https://arxiv.org/abs/2310.08560' }, { label: 'MemFS docs', url: 'https://github.com/letta-ai/letta-docs-md/blob/main/concepts/memfs/index.md' }]),

  p('openclaw', 'OpenClaw', 'Personal Agent Runtime', '开源 · TypeScript', `面向多渠道个人助手的集成式 Agent runtime：统一 model/provider、工具、session、skills、compaction、memory、channel delivery 和 Gateway。`, `flowchart TB\n  CH[CLI / chat channels] --> GW[Gateway / routing]\n  GW --> SM[Session manager]\n  SM --> ER[Embedded agent runner]\n  ER --> AC[packages/agent-core]\n  ER --> LLM[src/llm providers]\n  ER --> TR[Tool + MCP runtime]\n  ER --> DB[(Session SQLite)]\n  DB --> EP[Episodic memory index]\n  EP --> DR[Dreaming / consolidation]\n  DR --> BM[MEMORY.md + USER.md]`, [
    { name: 'packages/agent-core/src/agent-loop.ts', what: '可复用 Agent loop。', how: '管理消息、模型响应、工具执行、流式结果与停止。', why: '把核心 loop 从具体产品入口抽离。' },
    { name: 'src/agents/embedded-agent-runner', what: '内置运行尝试、模型选择、参数归一化、compaction 与 session wiring。', how: '组合 agent-core、provider、prompt、tools 和 transcript。', why: '产品 runtime 统一掌控一次 run 的生命周期。' },
    { name: 'src/agents/sessions', what: 'Session 持久化、资源发现、extensions、skills、模板和工具渲染。', how: 'SQLite 保存 active rows；loader 构建会话资源 manifest。', why: '多渠道共享同一 session 语义和资源版本。' },
    { name: 'src/llm', what: '模型/provider transport。', how: '把规范化请求转换到各 provider，并处理流式响应和错误。', why: '模型切换不侵入 Agent 控制流。' },
    { name: 'memory architecture', what: 'episodic tier、index、dreaming、bootstrap/user model 和双 recall lane。', how: '交互/flush/transcript 进入带 provenance 的 episodic 层；确定性 gate 后由 bounded model consolidation 晋升。', why: '长期记忆既要自动成长，又要防止垃圾和注入污染。' }
  ], ['渠道消息经 Gateway 解析到 agent/session', 'session manager 读取历史、skills 和 bootstrap memory', 'embedded runner 组装 Prompt 与 provider 参数', 'agent-core loop 调模型并执行 tools，可接受 streaming steering', 'session/checkpoint 写入 SQLite，候选 memory 后续由 dreaming consolidation'], ['集成 runtime 适合多渠道：每个渠道不用重复实现 loop/session/memory。', 'Memory 使用 provenance、session-kind gating 和 recall-loop prevention，明确处理记忆污染。'], ['集成面很大，Agent runtime、Gateway、渠道和插件演进耦合。', '官方文档承认 owner turn 内对 tool/web 派生内容尚未实现完整 origin taint 传播。'], ['把 trust provenance 贯穿 tool result 到 assistant output；加强模块 contract 与 conformance tests。'], `比 LangGraph 更像完整个人 Agent 产品；可以借鉴 LangGraph 的状态图思想，但 OpenClaw 自己拥有 runtime。`, [{ label: 'Repository', url: 'https://github.com/openclaw/openclaw' }, { label: 'Runtime architecture', url: 'https://github.com/openclaw/openclaw/blob/main/docs/agent-runtime-architecture.md' }, { label: 'Memory architecture', url: 'https://github.com/openclaw/openclaw/blob/main/docs/concepts/memory-architecture.md' }]),

  p('hermes', 'Hermes Agent', 'Self-improving Agent', '开源 · Python', `Nous Research 的模型无关个人 Agent，强调一个集中式 AIAgent loop、工具生态、可按需加载 skills、持久 memory、子 Agent 和多渠道运行。`, `flowchart TB\n  UI[TUI / Gateway / channels] --> AA[AIAgent]\n  AA --> PB[prompt_builder.py]\n  AA --> PA[Provider/API modes]\n  AA --> TD[Tool dispatch / MCP]\n  AA --> CA[Compression / retries / fallback]\n  AA --> MM[memory_manager.py]\n  AA --> SK[Skills]\n  TD --> SUB[Child agents]\n  MM --> AA`, [
    { name: 'run_agent.py / AIAgent', what: '核心 orchestration loop。', how: '负责 Prompt、可中断模型调用、工具并发、历史、压缩、fallback、父子预算和 memory flush。', why: '集中控制让多 provider 和多工具行为保持一致。' },
    { name: 'agent/prompt_builder.py', what: '组装系统 Prompt、工具/技能和运行时上下文。', how: '根据 provider/API mode 和可用资源构建有效请求。', why: 'Prompt 逻辑与 loop 执行分离。' },
    { name: 'model_tools.py / tools', what: '本地工具、MCP 和工具配置。', how: '统一 schema、启用范围和 dispatch；支持并行 tool calls。', why: '扩展行动能力而不修改模型。' },
    { name: 'memory_manager.py / provider', what: '持久 memory 读取、写入和 provider 接入。', how: '在 compaction 前 flush，支持搜索过往对话和外部 memory provider。', why: '避免长会话压缩丢失值得保留的信息。' },
    { name: 'Skills', what: '按需加载程序性知识，可由 Agent 从成功工作流中创建。', how: '启动只暴露 metadata，命中后加载正文；与常驻 factual memory 分离。', why: '降低常驻 token，并形成自我改进闭环。' }
  ], ['入口恢复 session 并由 prompt builder 组装上下文', 'AIAgent 选择 provider/API mode 发起可取消调用', 'tool calls 串行或线程池并发执行并写回历史', '达到阈值时压缩，压缩前 flush memory', '主模型失败可切换 fallback；子 Agent 使用继承的预算'], ['集中 loop 易于统一 provider fallback、取消和工具并发。', 'skills/memory 分离对应 procedural/factual knowledge 的不同加载成本。'], ['核心 AIAgent 承担很多职责，策略耦合和测试面大。', '自动 skill/memory 可能固化错误；不同 provider 工具协议存在兼容成本。'], ['进一步模块化 loop policy；技能评估与版本；来源可信度和 memory rollback。'], `与 OpenClaw 都是完整个人 Agent；Hermes 更偏 Python 单体 loop 与自学习 skills，OpenClaw 更偏多渠道集成 runtime 和分层 memory。`, [{ label: 'Repository', url: 'https://github.com/NousResearch/hermes-agent' }, { label: 'Skills guide', url: 'https://github.com/NousResearch/hermes-agent/blob/main/website/docs/guides/work-with-skills.md' }]),

  p('claude-code', 'Claude Code', 'Coding Agent Product', '闭源产品 · 官方公开架构', `围绕 Claude 模型的 agentic harness：读取项目上下文、调用文件/搜索/终端/Web 工具、验证结果，并通过权限、会话和扩展机制完成编码任务。`, `flowchart TB\n  User --> Loop[Gather context → Act → Verify]\n  Loop --> Model[Claude models]\n  Loop --> Tools[Read/Edit/Search/Bash/Web]\n  Tools --> Gate[Permission system]\n  Gate --> Env[Local / Cloud / Remote]\n  Loop --> Context[CLAUDE.md + files + memory + skills]\n  Loop --> Session[(JSONL session + snapshots)]\n  Context --> Compact[Compaction]\n  Compact --> Loop`, [
    { name: 'Agentic loop', what: '收集上下文、行动、验证并循环。', how: '模型根据工具 observation 调整下一步，用户可随时 interrupt/steer。', why: '代码任务需要不断从真实环境获得反馈。' },
    { name: 'Built-in tools', what: '文件、搜索、执行、Web 和代码智能工具。', how: '模型发起 tool use，经权限后在选定环境执行。', why: '模型本身只能生成文本，工具让它能改变和验证代码。' },
    { name: 'Context system', what: '历史、文件、命令输出、CLAUDE.md、auto memory、skills 和 MCP descriptions。', how: '启动加载常驻内容，路径规则/skills 按需加载，接近上限时清理大工具输出并 compaction。', why: '让模型获得项目知识同时管理有限窗口。' },
    { name: 'Session persistence', what: '本地 JSONL 记录消息、tool use/result，并对改动文件做快照。', how: '事件支持 resume、rewind、fork；工作树/目录界定 session。', why: '长任务可恢复，用户可回退和分叉探索。' },
    { name: 'Extensions', what: 'CLAUDE.md、rules、skills、hooks、MCP、subagents。', how: '分别解决常驻规则、路径规则、程序知识、确定性边界、外部工具和上下文隔离。', why: '用不同机制承载不同生命周期的信息和控制。' }
  ], ['用户目标进入 agentic loop', '先用搜索/读取工具建立最小项目上下文', '模型提出 edit/bash 等行动，经权限系统执行', '测试或工具结果返回成为下一轮 observation', '完成时给出结果；session JSONL/快照支持恢复与回退'], ['把代码库和终端视为可验证环境，强调 gather-act-verify。', '文件化规则/memory/skills 易审计且可版本控制；subagent 隔离大上下文。'], ['Claude Code 不是开源项目，无法可靠描述其未公开内部源码和调度实现。', '文件化指令仍只是上下文，不是强制策略；compaction 可能丢失会话细节。'], ['公开分析必须标注证据边界；强制约束放 hooks/permissions/CI；长期规则保持精炼。'], `与 OpenHands 同属 coding agent，但 Claude Code 是产品级 harness；OpenHands 的 sandbox/action-observation runtime 更开放可研究。`, [{ label: 'How Claude Code works', url: 'https://code.claude.com/docs/en/how-claude-code-works' }, { label: 'Memory docs', url: 'https://code.claude.com/docs/en/memory' }, { label: 'Context docs', url: 'https://code.claude.com/docs/en/context-window' }]),

  p('openhands', 'OpenHands', 'Coding Agent / Sandbox', '开源 · Python/TypeScript', `开放的编码 Agent 平台，核心学习点是 Action/Observation 事件流与客户端—容器 runtime 的安全执行边界。`, `flowchart LR\n  UI --> Backend\n  Backend --> Agent\n  Agent --> ES[EventStream]\n  ES -->|REST action| RT[Runtime client]\n  subgraph Sandbox\n    RT --> Bash\n    RT --> Browser\n    RT --> Files\n    RT --> Plugins\n  end\n  RT -->|observation| ES\n  ES --> Agent`, [
    { name: 'Agent', what: '根据 state/events 生成 Action。', how: 'LLM policy 将用户目标和 observations 转成 shell、file、browser 等 action。', why: '把决策与执行环境分离。' },
    { name: 'EventStream', what: '连接用户、Agent 和 Runtime 的 Action/Observation 总线。', how: '按事件追加状态并分发给订阅者。', why: '支持回放、UI 更新和解耦。' },
    { name: 'Runtime interface', what: '统一 bash、browser、filesystem、plugin 行动。', how: 'backend client 通过 REST 与 sandbox 内 ActionExecutor 通信。', why: '同一 Agent 可使用 Docker、本地或远程 runtime。' },
    { name: 'ActionExecutor', what: '在容器中执行具体 action。', how: '初始化 shell/browser/Jupyter/plugins，返回规范化 observation。', why: '把任意代码执行隔离在宿主之外。' },
    { name: 'Workspace', what: '任务可见的文件与运行环境。', how: '挂载或创建隔离目录，限制 Agent 能访问的范围。', why: '安全、复现和多用户隔离。' }
  ], ['Agent 从 EventStream 读取用户与历史 observations', '生成结构化 Action', 'Backend 经 REST 发给容器内 ActionExecutor', '执行器在 bash/browser/filesystem 执行并返回 Observation', 'Observation 进入 EventStream，Agent 再决策直到完成'], ['client-server runtime 允许真正隔离任意代码执行。', 'Action/Observation 事件模型比只保存聊天文本更适合回放。'], ['容器配置、镜像构建和远程 runtime 增加运维复杂度。', 'sandbox 安全取决于挂载、网络、权限和内核隔离。'], ['更强 VM 隔离、资源/网络策略、事件 schema 版本和可复现环境镜像。'], `可作为研究 coding agent runtime 的开放参照；与 Claude Code 的公开产品架构进行黑盒对比。`, [{ label: 'Repository', url: 'https://github.com/All-Hands-AI/OpenHands' }, { label: 'Runtime architecture', url: 'https://github.com/OpenHands/docs/blob/main/openhands/usage/architecture/runtime.mdx' }]),

  p('autogen', 'AutoGen', 'Multi-agent Framework', '开源 · Maintenance mode', `微软研究推出的分层多 Agent 框架：Core 提供消息传递和本地/分布式 runtime，AgentChat 提供 group chat 等高层模式。官方当前建议新项目评估 Microsoft Agent Framework。`, `flowchart TB\n  App --> AC[AgentChat]\n  AC --> Core[Core API]\n  Core --> Msg[Messages / subscriptions]\n  Core --> RT[Single-threaded or distributed runtime]\n  AC --> Teams[RoundRobin / Selector / Swarm]\n  Core --> Ext[Model clients / tools / executors]`, [
    { name: 'Core API', what: 'event-driven agents、message passing、runtime。', how: 'agent type/id、direct messages、topics/subscriptions 和 runtime lifecycle。', why: '支持低层、分布式、多语言 Agent 系统。' },
    { name: 'AgentChat', what: 'AssistantAgent、teams、termination 和 handoff。', how: '在 Core 之上组合 RoundRobinGroupChat、SelectorGroupChat、Swarm 等模式。', why: '快速原型常见多 Agent 会话。' },
    { name: 'Extensions', what: '模型客户端、代码执行器、工具和缓存。', how: 'provider 包实现 core protocols。', why: '运行时与供应商/环境解耦。' }
  ], ['AgentChat 创建 Agents 与 Team', 'Team runtime 分发消息并选择下一 speaker', 'Agent 调模型或工具产生消息/事件', 'termination condition 判断结束', '结果和状态可保存/恢复'], ['分层 API 允许高层快速使用和低层自定义。', '消息传递适合研究复杂协作协议。'], ['多 Agent 容易形成聊天噪音和高成本；AutoGen 当前处于维护模式。'], ['新项目评估 Microsoft Agent Framework；迁移时保留 message/tool/state contracts。'], `与 LangGraph 的显式状态图相比，AutoGen/AgentChat 更偏 agent-to-agent 消息和 conversation patterns。`, [{ label: 'Repository and status', url: 'https://github.com/microsoft/autogen' }])
];

const PROJECT_BY_ID = Object.fromEntries(PROJECT_CASES.map(project => [project.id, project]));
