const TEXTBOOK_CHAPTERS = [
  {
    id: 'book-agent', number: '01', title: 'Agent 的本质：一个由模型驱动的控制系统', tag: '基础原理',
    intro: '先把 Agent 从“会思考的人”还原成一个可以观察、测试和限制的程序。',
    sections: [
      { title: '从 LLM call 到 Agent', paragraphs: ['LLM call 是一次函数调用：给模型一组消息，收到一段输出。Chain 把多个调用串起来；Workflow 用代码规定路径；Agent 则把“下一步做什么”交给模型选择，但工具执行和状态写入仍由宿主程序负责。', '因此 Agent 的核心不是模型本身，而是一个闭环：模型读取当前上下文，产生文本或结构化 action，执行器验证并执行 action，把 observation 写回状态，再次调用模型。这个闭环必须有预算、终止和失败语义。'], diagram: `flowchart LR\n  U[用户目标] --> C[Context Builder]\n  C --> M[Model]\n  M -->|final| A[最终答案]\n  M -->|tool_call| V[Schema/Policy 校验]\n  V --> T[Tool Runtime]\n  T --> S[State 更新]\n  S --> C` },
      { title: '最小 Agent loop', paragraphs: ['模型输出“我要调用天气工具”不是执行结果。执行器必须校验工具名、参数、身份和预算；工具返回的数据也必须被标记为 observation，不能自动升级为系统指令。', '最小实现不需要框架：一个 list 保存 messages，一个 while 控制循环，一个 registry 映射工具名到函数，一个 policy 决定是否允许执行。框架的价值是把这些边界做成可组合的 runtime。'], code: `from dataclasses import dataclass\n\n@dataclass\nclass ToolCall:\n    name: str\n    arguments: dict\n\nfor step in range(MAX_STEPS):\n    response = model.invoke(messages, tools=tool_schemas)\n    if response.final_text:\n        return response.final_text\n\n    for call in response.tool_calls:\n        validate_schema(call)\n        authorize(actor, call)\n        result = tools[call.name](**call.arguments)\n        messages += [response.message, tool_message(call, result)]\n\nraise BudgetExceeded('agent did not finish')` },
      { title: '什么时候不用 Agent', paragraphs: ['如果路径是固定的，例如“解析表单 → 校验字段 → 写数据库 → 返回结果”，用普通代码或 Graph 更可靠。只有当输入不确定、工具选择不确定、步骤数量不确定时，才把局部决策交给模型。', '一个实用架构通常是 deterministic shell + agentic core：外层负责认证、预算、状态、审计和副作用；内层模型负责分类、查询改写、选择工具或生成候选方案。'] }
    ]
  },
  {
    id: 'book-llm', number: '02', title: 'LLM 底层：Token、Transformer、解码与工具协议', tag: '底层原理',
    intro: '理解模型输入输出的物理边界，才能解释上下文、延迟、成本和幻觉。',
    sections: [
      { title: '从文字到 logits', paragraphs: ['模型接收的不是“文字”，而是 token id 序列。Embedding 把 token id 变成向量；Transformer 层通过带因果 mask 的 self-attention，让当前位置只能读取它之前的 token；最后的线性层产生下一个 token 的 logits。', '解码阶段把 logits 转成概率，再用 greedy、temperature、top-p 等策略选出一个 token，追加到序列，循环直到 stop token 或达到输出上限。模型不是一次性写完答案，而是反复执行 next-token prediction。'], diagram: `flowchart LR\n  X[文本] --> Tok[Tokenizer]\n  Tok --> E[Token embeddings + position]\n  E --> Tr[Transformer blocks]\n  Tr --> L[LM head / logits]\n  L --> D[Decode / sample]\n  D --> Y[下一个 token]\n  Y --> Tok` },
      { title: 'Attention 为什么能“看上下文”', paragraphs: ['对每个位置，输入经过三个线性投影得到 Q、K、V。Q 与所有 K 做点积得到相关性，再经过缩放和 softmax 得到权重，最后对 V 加权求和。多头注意力让不同 head 学习不同关系。', '它不是检索数据库，也没有天然的事实校验能力。attention 只表达当前计算中哪些 token 对哪些 token 有影响；长上下文中的位置、重复、冲突和噪音都会影响模型行为。'], code: `scores = (Q @ K.T) / sqrt(head_dim)\nscores = scores + causal_mask  # 未来 token 设为 -inf\nweights = softmax(scores, axis=-1)\noutput = weights @ V` },
      { title: 'Tool calling 是协议，不是能力越权', paragraphs: ['现代模型可以返回结构化 tool call：工具名、JSON 参数和调用 ID。模型只提出 action，宿主程序才拥有执行权。正确的顺序是 parse → schema validate → policy authorize → execute → normalize result → append observation。', '如果模型输出看似成功但没有结构化调用，不能假装工具执行过；如果工具返回包含恶意指令，也不能把它与 system/user 指令混在一起。消息 role 和来源标记是安全边界的一部分。'], diagram: `sequenceDiagram\n  participant M as Model\n  participant R as Runtime\n  participant P as Policy\n  participant T as Tool\n  M->>R: tool_call(name,args)\n  R->>P: validate + authorize\n  P-->>R: allow / deny / confirm\n  R->>T: execute once\n  T-->>R: result envelope\n  R->>M: tool observation` }
    ]
  },
  {
    id: 'book-rag', number: '03', title: 'RAG 的真正实现：从原始文档到可引用答案', tag: '知识增强',
    intro: 'RAG 不是“接一个向量库”，而是一条有数据版本、权限和评估指标的检索系统。',
    sections: [
      { title: '离线 ingest 与在线 query', paragraphs: ['离线阶段负责把 source of truth 变成可检索索引：解析、清洗、切分、抽取 metadata、生成 embedding、写入向量/倒排存储。在线阶段负责理解问题、过滤权限、召回候选、排序、组装 context 和生成答案。', '离线和在线必须通过版本连接：source_version、chunker_version、embedding_model_version 和 retriever_version 需要能进入 trace，否则线上回答无法解释。'], diagram: `flowchart TB\n  subgraph Offline[离线索引]\n    S[Source] --> P[Parse / OCR]\n    P --> C[Chunk + metadata]\n    C --> E[Embedding]\n    E --> I[(Vector + BM25 index)]\n  end\n  subgraph Online[在线问答]\n    Q[Question] --> R[Rewrite / filter]\n    R --> I\n    I --> RR[Rerank]\n    RR --> CTX[Context builder]\n    CTX --> LLM[Generator]\n  end` },
      { title: '为什么 chunking 决定上限', paragraphs: ['chunk 太大，检索结果包含大量无关内容，模型需要在上下文中重新定位；chunk 太小，定义、条件和例外会被拆开，召回到的片段缺少完整语义。结构感知切分应优先保留标题层级、段落、表格行、代码块和来源位置。', '每个 chunk 至少要携带 source_id、版本、页面/章节和权限 metadata。metadata filter 不是回答之后再做的补救，而是召回边界的一部分。'], code: `def make_chunks(document):\n    for section in split_by_headings(document):\n        for block in split_preserving_tables_and_code(section):\n            yield {\n                'text': block.text,\n                'source_id': document.id,\n                'section': section.title,\n                'version': document.version,\n                'acl': document.acl,\n            }` },
      { title: '召回、排序和生成要分开评估', paragraphs: ['Retriever 负责把相关证据带回来，reranker 负责在候选中排序，generator 负责根据证据回答。最终答案错，不代表一定是模型错：可能是正确片段没召回、召回了错误版本、排序把关键片段压下去了，或模型没有使用证据。', '建议为数据集保存 expected_sources、关键事实和禁止结论。分别计算 recall@k、MRR/nDCG、citation completeness、faithfulness 和 answer correctness。只有这样才能定位瓶颈。'], diagram: `flowchart LR\n  Q[Query] --> Ret[Recall candidates]\n  Ret --> Rank[Rerank]\n  Rank --> G[Grounded generation]\n  G --> V[Claim / citation validator]\n  V -->|不足| Ret\n  V -->|通过| O[Answer]` }
    ]
  },
  {
    id: 'book-memory', number: '04', title: 'Memory 与 Context Engineering：信息如何跨回合生存', tag: '状态与记忆',
    intro: 'Memory 不是把历史消息永久堆进 Prompt，而是有生命周期、来源和权限的数据系统。',
    sections: [
      { title: '三种“记忆”', paragraphs: ['短期状态是当前 thread 的工作台：问题、计划、工具结果、未完成步骤。长期记忆是跨 session 的稳定偏好或事实。外部事实属于数据库或知识库，应通过检索获取。三者的写入者、读取频率和删除规则完全不同。', '例如“用户喜欢简洁回答”可以是长期偏好；“订单已发货”应从业务系统读取；“本轮已经查过订单”应放在 thread state。把订单状态写成长期 memory 会造成过时事实。'], diagram: `flowchart TB\n  T[Thread state] -->|summarize / promote| C[Memory policy]\n  C --> L[(Long-term memory)]\n  Q[Current query] --> B[Context builder]\n  L --> B\n  DB[(Business DB / RAG)] --> B\n  T --> B\n  B --> M[Model]` },
      { title: 'Context builder 是一个编译器', paragraphs: ['可以把 context builder 理解成编译器：输入是多种来源的事实和规则，输出是当前模型调用需要的 message/tool/context。它负责选择、排序、压缩、去重、脱敏，并记录 context manifest。', '一个可靠的 context builder 应有 token budget 和优先级。例如先保留 system policy、当前目标、未完成任务和最新证据，再压缩旧对话；不要用字符串拼接隐藏这些决策。'], code: `def build_context(state, budget):\n    items = [system_policy(state.actor), state.goal]\n    items += latest_unfinished_steps(state)\n    items += authorized_retrieval(state.query, state.actor)\n    items += recent_tool_results(state)\n    items = dedupe_and_mark_provenance(items)\n    return fit_budget(sort_by_priority(items), budget)` },
      { title: '写入记忆需要门槛', paragraphs: ['记忆写入应该有明确政策：谁可以写、什么信息可写、置信度如何、冲突如何处理、何时过期、用户如何查看和删除。让模型“自动总结一切”会把猜测、恶意文档和临时状态提升成长期事实。', '一个稳妥的策略是：用户明确表达或确认的偏好可直接进入候选；模型推断的事实进入待审核候选；工具/网页内容必须携带来源和信任等级，不能因为被模型复述就自动晋升。'] }
    ]
  },
  {
    id: 'book-graph', number: '05', title: 'LangGraph Runtime：StateGraph、Pregel、Checkpoint 与恢复', tag: '运行时',
    intro: '从“写一个 Agent”进入“设计一个可恢复的 Agent runtime”。',
    sections: [
      { title: 'Graph 的三个原语', paragraphs: ['State 是跨节点共享的快照；Node 是接收 state 并返回 update 的函数；Edge 决定下一步节点。节点可以包含模型、数据库或普通代码，Graph 本身不要求每个节点都智能。', '把节点设计成小而可测试的函数，可以把确定性校验、模型决策、工具执行和人工审批组合成一条清晰的状态机。'], diagram: `flowchart LR\n  START --> Classify\n  Classify -->|knowledge| Retrieve\n  Classify -->|write| Prepare\n  Retrieve --> Answer\n  Prepare -->|interrupt| Approve\n  Approve --> Execute\n  Execute --> Readback\n  Answer --> END\n  Readback --> END` },
      { title: 'super-step 与 Pregel 思维', paragraphs: ['LangGraph 的底层执行可以用消息传递来理解：节点收到输入后被激活，执行结果写入 channels 并沿边传播；同一轮中可并行执行的节点属于同一个 super-step。共享字段有并发写入时，需要 reducer 定义如何合并。', '这与普通的 `for node in nodes` 不同：runtime 需要管理可恢复的任务、节点写入、错误和下一轮激活状态。理解 super-step 后，才能正确理解并行 fan-out 和 checkpoint 边界。'], code: `class State(TypedDict):\n    question: str\n    sources: Annotated[list[Source], operator.add]\n\n# fan-out: each research node returns sources\n# reducer: operator.add merges parallel writes\n# next super-step: synthesize reads the merged state` },
      { title: 'Checkpoint 与 interrupt 的真实语义', paragraphs: ['Checkpoint 是某个 thread 在 super-step 边界的状态快照，不是“保存了最终答案”。它还需要关联 parent checkpoint、pending tasks、metadata 和写入记录。interrupt 应该在副作用之前或幂等边界上发生，resume 时必须能区分已完成和未完成动作。', '因此高风险流程通常是 canonicalize → policy classify → interrupt/confirm → execute once → read-back → receipt。不要在模型生成的自然语言中直接执行数据库写入。'], diagram: `sequenceDiagram\n  participant G as Graph\n  participant CP as Checkpointer\n  participant H as Human\n  participant DB as External system\n  G->>CP: save draft state\n  G->>H: interrupt with preview\n  H-->>G: resume(approved)\n  G->>DB: idempotent execute\n  DB-->>G: read-back\n  G->>CP: save receipt state` }
    ]
  },
  {
    id: 'book-open-source', number: '06', title: 'Agent 架构解剖：OpenClaw、Hermes、Claude Code', tag: '开源系统',
    intro: '把三个真实系统当作架构教材：它们都使用模型和工具，但在运行时、记忆和扩展方式上做了不同取舍。',
    sections: [
      { title: 'OpenClaw：集成式 runtime + 分层 memory', paragraphs: ['根据 OpenClaw 官方架构文档，内置 Agent runtime 由 OpenClaw 自己拥有：`src/agents/` 负责 Agent 运行时，`src/llm/` 负责模型/provider transport，`packages/agent-core/` 提供可复用的 loop、harness types、messages、compaction、skills 和 session storage contracts。', '它的关键设计是把“模型调用、工具 wiring、Prompt assembly、session management、channel delivery”放在同一 runtime 边界内。这样做适合个人助手和多入口渠道，因为 Telegram、CLI 或其他 channel 不需要各自实现一套 loop。代价是 runtime 需要承担更多集成复杂度。', '官方 memory architecture 进一步采用 plain files + SQLite index 的分层设计：bootstrap 文件和用户模型用于低成本常驻上下文，episodic notes 作为事实候选，dreaming/consolidation 负责去重、合并和晋升。它还强调 provenance、信任等级和 recall-loop prevention，避免被注入的内容反复变成新记忆。'], diagram: `flowchart TB\n  CH[Channels] --> SM[Session manager]\n  SM --> AR[Embedded agent runner]\n  AR --> PB[Prompt / skills / compaction]\n  AR --> LLM[Provider transport]\n  AR --> TR[Tool runtime]\n  AR --> TX[Transcript + session storage]\n  TX --> EP[Episodic memory + SQLite index]\n  EP --> DG[Dreaming / consolidation]\n  DG --> BM[MEMORY.md / USER.md]` , links: [{ text: 'OpenClaw runtime architecture', url: 'https://github.com/openclaw/openclaw/blob/main/docs/agent-runtime-architecture.md' }, { text: 'OpenClaw memory architecture', url: 'https://github.com/openclaw/openclaw/blob/main/docs/concepts/memory-architecture.md' }] },
      { title: 'Hermes：单体 Agent loop + 可学习的技能/记忆', paragraphs: ['Hermes Agent 的核心学习价值是“自我改进闭环”：模型可以从经验中创建 skills、持久化知识、搜索过去对话，并形成用户模型；同时通过 provider abstraction 支持不同模型入口，通过 CLI/TUI 和 Telegram 等渠道提供交互。', '从官方开发者文档描述的实现看，`AIAgent` loop 集中负责 Prompt assembly、tool dispatch、provider/API mode 选择、可中断模型调用、串行/并发工具、压缩、重试、fallback、父子 Agent budget 和 memory flush。这是一个偏“单体 orchestrator”的取舍：逻辑集中，容易理解和扩展，但核心循环文件会承载很多策略。', 'Hermes 把 skills 与 memory 分开：skill 是按需加载的程序性知识，memory 是自动注入的事实知识。这个分离解决了两个相反问题：技能可以很长但不必每轮付 token，记忆需要稳定但必须保持紧凑。'], diagram: `flowchart LR\n  UI[CLI / Telegram] --> A[AIAgent loop]\n  A --> PB[Prompt builder]\n  A --> P[Provider adapter]\n  A --> TD[Tool dispatch]\n  A --> CM[Compression / fallback]\n  A --> MF[Memory flush]\n  A --> SK[On-demand skills]\n  SK --> A` , links: [{ text: 'Hermes repository', url: 'https://github.com/NousResearch/hermes-agent' }, { text: 'Hermes Agent loop internals', url: 'https://github.com/xgaisystems/hermes-agent-NousResearch/blob/main/website/docs/developer-guide/agent-loop.md' }, { text: 'Hermes skills vs memory', url: 'https://github.com/NousResearch/hermes-agent/blob/main/website/docs/guides/work-with-skills.md' }] },
      { title: 'Claude Code：agentic harness + 文件化上下文', paragraphs: ['Claude Code 官方将自己定义为围绕 Claude 的 agentic harness：模型负责理解和决策，工具负责读写文件、搜索、执行命令、访问 Web 和外部服务，harness 负责上下文管理、权限和执行环境。其典型 loop 是 gather context → take action → verify results，并根据结果重复。', '它的上下文不仅是聊天历史，还包括文件内容、命令输出、CLAUDE.md、auto memory、skills、MCP tool descriptions 和系统指令。会话以 JSONL 记录，支持 resume、rewind 和 fork；上下文接近上限时会清理旧工具输出并 compaction，同时保留关键请求和代码片段。', 'Claude Code 的设计重点不是复杂 Graph，而是让工作区成为可读取的 context surface：CLAUDE.md 放稳定规则，auto memory 放跨会话经验，skills 按需加载，MCP 扩展工具，hooks 在工具边界插入策略。它适合代码任务，因为文件系统、终端和 Git 就是可验证的外部环境。'], diagram: `flowchart TB\n  U[User task] --> H[Harness]\n  H --> CTX[Project files + CLAUDE.md + memory + skills]\n  CTX --> M[Claude model]\n  M -->|read/search/edit/run| G[Permission gate]\n  G --> E[Execution environment]\n  E --> R[Result / test output]\n  R --> H\n  H -->|JSONL session + compaction| P[Resume / rewind / fork]` , links: [{ text: 'How Claude Code works', url: 'https://code.claude.com/docs/en/how-claude-code-works' }, { text: 'Claude Code memory', url: 'https://code.claude.com/docs/en/memory' }, { text: 'Claude Code subagents', url: 'https://code.claude.com/docs/en/sub-agents' }] },
      { title: '三者的架构取舍', paragraphs: ['OpenClaw 更强调多渠道个人助手和分层持久记忆；Hermes 更强调单体 Agent loop、provider 灵活性和 skills/memory 学习闭环；Claude Code 更强调受权限控制的代码执行环境、文件化项目上下文和可回放会话。', '它们的共同结构是：model adapter、tool registry、context builder、session/state、compaction、permission boundary、extension mechanism 和 observability。学习时应先抽出共同骨架，再研究不同产品为何把边界放在不同位置。'], diagram: `flowchart LR\n  Model[Model adapter] --- Loop[Agent loop]\n  Loop --- Tools[Tool registry]\n  Loop --- Context[Context builder]\n  Loop --- State[Session / memory]\n  Tools --- Policy[Permission / confirmation]\n  State --- Obs[Trace / replay]\n  Loop --- Ext[Skills / MCP / plugins]` }
    ]
  },
  {
    id: 'book-production', number: '07', title: '生产级 Agent：评估、安全、观测与性能', tag: '工程化',
    intro: '可靠 Agent 的标准不是“看起来聪明”，而是失败可解释、状态可恢复、动作可审计。',
    sections: [
      { title: '评估要按故障面拆分', paragraphs: ['为 Agent 评估定义 task success 还不够。至少拆成：意图/路由、工具选择、参数合法性、检索相关性、证据引用、最终正确性、权限拒绝、成本和延迟。每项都需要可复现样例。', 'LLM-as-judge 可以帮忙扩展评估，但不能替代人工校准。参考答案、关键事实、expected tool、禁止动作和 expected sources 应成为数据集的一部分。'], diagram: `flowchart TB\n  Dataset[Golden + boundary + attack cases] --> Run[Replay agent]\n  Run --> T[Tool metrics]\n  Run --> R[Retrieval metrics]\n  Run --> A[Answer metrics]\n  Run --> S[Safety metrics]\n  T --> Gate[Regression gate]\n  R --> Gate\n  A --> Gate\n  S --> Gate` },
      { title: 'Trace 应该记录什么', paragraphs: ['一条完整 trace 至少要有 run_id、actor/tenant、model/provider/version、Prompt/version、每轮输入输出、tool call 参数、tool result envelope、retrieval query/doc IDs/scores、state updates、耗时、token 和错误。敏感内容要脱敏，但不能把关键诊断字段一起删掉。', '观测系统的目的不是展示漂亮瀑布图，而是支持三个动作：复现失败、比较版本、发现线上漂移。'] },
      { title: '安全边界与副作用控制', paragraphs: ['模型生成的内容不应直接成为 SQL、shell、HTTP 写入或文件路径。所有副作用都要经过服务端授权、参数校验、资源范围校验和幂等执行；高风险动作增加预览和确认。', 'Prompt injection 的防御重点是信任等级和执行边界：用户/系统指令、检索数据、工具结果、网页内容不能混为一种来源。即使模型被诱导，也应该因为 policy gate 无权执行。'], code: `payload = canonicalize(model_output)\npolicy = classify(actor, payload)\nif policy.requires_confirmation:\n    receipt = interrupt(preview(payload))\n    if not receipt.approved:\n        return 'cancelled'\nresult = execute_once(idempotency_key, payload)\nreturn read_back_and_issue_receipt(result)` },
      { title: '性能优化的正确顺序', paragraphs: ['先测完整链路，再优化。首 token 延迟通常受模型首包、Prompt 长度和网络影响；总耗时可能由多轮 Agent loop、检索、rerank、工具 API 和人工等待组成。只降低模型 temperature 不会解决这些瓶颈。', '常见优化是：小模型做分类/查询改写，大模型做最终合成；动态 top-k；并行独立检索；缓存只读结果；为每个请求设置 deadline 和预算；不必要时尽早结束。每次优化都要同时看质量、成本和 P95 延迟。'] }
    ]
  },
  {
    id: 'book-capstone', number: '08', title: '毕业路线：从源码复刻到企业 Agent', tag: '综合项目',
    intro: '用一个有真实副作用的系统检验是否真正掌握，而不是只会调用 demo。',
    sections: [
      { title: '四个递进实现', paragraphs: ['第一步，手写一个三步 Agent loop；第二步，加入 2-Step RAG 和 citation validator；第三步，用 LangGraph 加入 state、checkpoint、interrupt 和 streaming；第四步，把查询、写入、权限、审计、评估和观测组成企业助手。', '每一步都保留上一版作为对照。你要能说明新框架解决了什么问题，也能指出它引入了什么成本。'], diagram: `flowchart LR\n  L1[手写 loop] --> L2[RAG + citations]\n  L2 --> L3[LangGraph state/checkpoint]\n  L3 --> L4[权限/审批/观测/评估]\n  L4 --> L5[可部署企业 Agent]` },
      { title: '毕业项目验收清单', paragraphs: ['知识问答必须带来源，证据不足时拒答；SQL 工具默认只读；写入动作必须 canonicalize、确认、幂等执行和 read-back；每个 Agent run 有预算和 deadline；断线可以恢复；每个失败样例有 trace；文档更新和权限变化能反映到检索。', '最终 README 要包含架构图、数据模型、威胁模型、运行步骤、测试集、已知限制、成本估算和回滚方案。陌生开发者能运行，才算完成。'] },
      { title: '掌握的判断标准', paragraphs: ['你不需要记住每个框架 API，但应该能从零设计：消息协议、工具 schema、状态 schema、context builder、loop budget、Graph topology、memory policy、RAG evaluation 和 permission gate。', '当换成另一个模型或框架时，你仍能沿着同一条链路分析：模型看到了什么？做了什么决策？谁执行了副作用？状态保存在哪里？证据和失败如何被观察？这才是 Agent 能力的核心。'] }
    ]
  }
];
